export type IpaSound = {
  symbol: string;
  name: string;
  type: "vowel" | "diphthong" | "consonant";
  voiced: boolean;
  mouth: string;
  mouthVi: string;
  tongue: string;
  tongueVi: string;
  words: string[];
  sentence: string;
};

export const IPA_SOUNDS: IpaSound[] = [
  {
    symbol: "/iː/",
    name: "long ee",
    type: "vowel",
    voiced: true,
    mouth: "Lips spread wide, almost smiling. Jaw nearly closed.",
    mouthVi: "Môi kéo rộng như đang cười. Hàm gần như đóng.",
    tongue: "Tongue high and forward, close to the hard palate. Hold it long.",
    tongueVi: "Lưỡi cao và đưa ra trước, gần vòm miệng. Giữ âm dài.",
    words: ["sheep", "seat", "leave", "beat"],
    sentence: "She needs a clean sheet of paper.",
  },
  {
    symbol: "/ɪ/",
    name: "short i",
    type: "vowel",
    voiced: true,
    mouth: "Lips relaxed and slightly open — do not smile.",
    mouthVi: "Môi thư giãn, hơi mở — đừng kéo môi cười.",
    tongue: "Tongue high but more central and relaxed. Very short sound.",
    tongueVi: "Lưỡi cao nhưng lùi vào giữa và thư giãn. Âm rất ngắn.",
    words: ["ship", "sit", "live", "bit"],
    sentence: "This little kid is sitting still.",
  },
  {
    symbol: "/æ/",
    name: "short a",
    type: "vowel",
    voiced: true,
    mouth: "Open your mouth wide and spread the lips.",
    mouthVi: "Mở miệng rộng và kéo môi sang hai bên.",
    tongue: "Tongue low and forward, jaw dropped.",
    tongueVi: "Lưỡi thấp và ra trước, hạ hàm.",
    words: ["cat", "bad", "man", "happy"],
    sentence: "That cat sat on a black mat.",
  },
  {
    symbol: "/ʌ/",
    name: "short u",
    type: "vowel",
    voiced: true,
    mouth: "Mouth relaxed and half open, lips neutral.",
    mouthVi: "Miệng thư giãn, mở nửa, môi trung tính.",
    tongue: "Tongue central and low. Short, punchy sound.",
    tongueVi: "Lưỡi ở giữa và thấp. Âm ngắn, dứt khoát.",
    words: ["cut", "bus", "love", "much"],
    sentence: "My brother loves running.",
  },
  {
    symbol: "/ə/",
    name: "schwa",
    type: "vowel",
    voiced: true,
    mouth: "Completely relaxed, barely open. The laziest English sound.",
    mouthVi: "Hoàn toàn thư giãn, mở rất ít. Âm 'lười' nhất trong tiếng Anh.",
    tongue: "Tongue rests in the middle. Always unstressed.",
    tongueVi: "Lưỡi nằm ở giữa. Luôn không nhấn.",
    words: ["about", "teacher", "banana", "support"],
    sentence: "A banana for the teacher.",
  },
  {
    symbol: "/uː/",
    name: "long oo",
    type: "vowel",
    voiced: true,
    mouth: "Lips rounded and pushed forward, small opening.",
    mouthVi: "Môi tròn và đẩy ra trước, khe hở nhỏ.",
    tongue: "Tongue high and back. Hold it long.",
    tongueVi: "Lưỡi cao và lùi về sau. Giữ âm dài.",
    words: ["fool", "food", "true", "blue"],
    sentence: "Two blue shoes.",
  },
  {
    symbol: "/ʊ/",
    name: "short oo",
    type: "vowel",
    voiced: true,
    mouth: "Lips lightly rounded, relaxed. Short.",
    mouthVi: "Môi tròn nhẹ, thư giãn. Âm ngắn.",
    tongue: "Tongue high-back but relaxed and central.",
    tongueVi: "Lưỡi cao-sau nhưng thư giãn, hơi vào giữa.",
    words: ["full", "book", "good", "put"],
    sentence: "Put the good book down.",
  },
  {
    symbol: "/e/",
    name: "short e",
    type: "vowel",
    voiced: true,
    mouth: "Mouth slightly open, lips relaxed and spread a little.",
    mouthVi: "Miệng hơi mở, môi thư giãn, kéo nhẹ.",
    tongue: "Tongue mid-high and forward.",
    tongueVi: "Lưỡi ở giữa-cao và ra trước.",
    words: ["bed", "said", "head", "many"],
    sentence: "Ten red pens.",
  },
  {
    symbol: "/ɔː/",
    name: "long aw",
    type: "vowel",
    voiced: true,
    mouth: "Lips rounded, jaw fairly open.",
    mouthVi: "Môi tròn, hàm mở khá rộng.",
    tongue: "Tongue low and back. Long sound.",
    tongueVi: "Lưỡi thấp và lùi sau. Âm dài.",
    words: ["thought", "law", "caught", "door"],
    sentence: "He bought a tall door.",
  },
  {
    symbol: "/ɜːr/",
    name: "r-coloured er",
    type: "vowel",
    voiced: true,
    mouth: "Lips slightly rounded, jaw mid.",
    mouthVi: "Môi hơi tròn, hàm ở giữa.",
    tongue: "Tongue tip curls slightly back without touching anything.",
    tongueVi: "Đầu lưỡi cuộn nhẹ về sau, không chạm vào đâu.",
    words: ["bird", "work", "learn", "nurse"],
    sentence: "The nurse learned first.",
  },
  {
    symbol: "/eɪ/",
    name: "ay diphthong",
    type: "diphthong",
    voiced: true,
    mouth: "Start half open, then close towards a smile.",
    mouthVi: "Bắt đầu mở nửa, rồi khép lại như cười.",
    tongue: "Glide from /e/ to /ɪ/ smoothly.",
    tongueVi: "Trượt từ /e/ sang /ɪ/ một cách mượt.",
    words: ["day", "make", "rain", "eight"],
    sentence: "They came late today.",
  },
  {
    symbol: "/oʊ/",
    name: "oh diphthong",
    type: "diphthong",
    voiced: true,
    mouth: "Start mid-open, round the lips as you finish.",
    mouthVi: "Bắt đầu mở giữa, tròn môi khi kết thúc.",
    tongue: "Glide from /o/ back and up to /ʊ/.",
    tongueVi: "Trượt từ /o/ lùi và lên /ʊ/.",
    words: ["go", "boat", "know", "phone"],
    sentence: "I know the old road home.",
  },
  {
    symbol: "/aɪ/",
    name: "eye diphthong",
    type: "diphthong",
    voiced: true,
    mouth: "Open wide, then close towards a smile.",
    mouthVi: "Mở rộng, rồi khép lại như cười.",
    tongue: "Glide from /a/ up to /ɪ/.",
    tongueVi: "Trượt từ /a/ lên /ɪ/.",
    words: ["time", "my", "five", "night"],
    sentence: "Five nights of my life.",
  },
  {
    symbol: "/θ/",
    name: "voiceless th",
    type: "consonant",
    voiced: false,
    mouth: "Tongue tip lightly between the teeth, blow air — no voice.",
    mouthVi: "Đầu lưỡi đặt nhẹ giữa hai hàng răng, thổi hơi — không rung.",
    tongue: "Tip touches the bottom of the upper teeth.",
    tongueVi: "Đầu lưỡi chạm mặt dưới của răng trên.",
    words: ["think", "three", "bath", "healthy"],
    sentence: "I think three things.",
  },
  {
    symbol: "/ð/",
    name: "voiced th",
    type: "consonant",
    voiced: true,
    mouth: "Same position as /θ/ but with vocal cords vibrating.",
    mouthVi: "Giống /θ/ nhưng dây thanh rung.",
    tongue: "Tongue tip between the teeth, buzzing.",
    tongueVi: "Đầu lưỡi giữa hai hàng răng, tạo tiếng rung.",
    words: ["this", "that", "mother", "weather"],
    sentence: "This is my mother.",
  },
  {
    symbol: "/v/",
    name: "vee",
    type: "consonant",
    voiced: true,
    mouth: "Top teeth touch the lower lip, voice buzzes through.",
    mouthVi: "Răng trên chạm môi dưới, dây thanh rung.",
    tongue: "Tongue is not involved — this is a lip-teeth sound.",
    tongueVi: "Lưỡi không tham gia — đây là âm môi-răng.",
    words: ["very", "love", "believe", "voice"],
    sentence: "Very lovely voice.",
  },
  {
    symbol: "/r/",
    name: "American r",
    type: "consonant",
    voiced: true,
    mouth: "Lips slightly rounded and pushed forward.",
    mouthVi: "Môi hơi tròn và đẩy ra trước.",
    tongue: "Tongue tip curls up and back but never touches the roof.",
    tongueVi: "Đầu lưỡi cuộn lên và về sau nhưng không chạm vòm miệng.",
    words: ["red", "very", "car", "worry"],
    sentence: "Robert reads rarely.",
  },
  {
    symbol: "/l/",
    name: "light l",
    type: "consonant",
    voiced: true,
    mouth: "Mouth relaxed and open.",
    mouthVi: "Miệng thư giãn và mở.",
    tongue: "Tongue tip presses the ridge behind the upper teeth.",
    tongueVi: "Đầu lưỡi ấn vào gờ sau răng trên.",
    words: ["light", "like", "fall", "little"],
    sentence: "Little Lily likes it.",
  },
  {
    symbol: "/ʃ/",
    name: "sh",
    type: "consonant",
    voiced: false,
    mouth: "Lips pushed forward and rounded, long airflow.",
    mouthVi: "Môi đẩy ra trước và tròn, hơi thổi dài.",
    tongue: "Tongue broad and close to the roof, slightly back of /s/.",
    tongueVi: "Lưỡi rộng, gần vòm miệng, lùi hơn /s/.",
    words: ["she", "shop", "fish", "nation"],
    sentence: "She should shop.",
  },
  {
    symbol: "/dʒ/",
    name: "j sound",
    type: "consonant",
    voiced: true,
    mouth: "Start with a small stop, then release into a buzz.",
    mouthVi: "Bắt đầu bằng một điểm chặn nhỏ, rồi bật ra tiếng rung.",
    tongue: "Tongue front touches the ridge, then releases.",
    tongueVi: "Phần trước lưỡi chạm gờ, rồi nhả ra.",
    words: ["job", "judge", "age", "bridge"],
    sentence: "John's job is a joy.",
  },
];

export type MinimalPair = { a: string; b: string; soundA: string; soundB: string; note: string; noteVi: string };

export const MINIMAL_PAIRS: MinimalPair[] = [
  { a: "ship", b: "sheep", soundA: "/ɪ/", soundB: "/iː/", note: "Short and relaxed vs long and smiling.", noteVi: "Ngắn, thư giãn so với dài, kéo môi." },
  { a: "sit", b: "seat", soundA: "/ɪ/", soundB: "/iː/", note: "Do not stretch the first one.", noteVi: "Đừng kéo dài âm đầu." },
  { a: "live", b: "leave", soundA: "/ɪ/", soundB: "/iː/", note: "Length changes the meaning completely.", noteVi: "Độ dài thay đổi hoàn toàn nghĩa." },
  { a: "bit", b: "beat", soundA: "/ɪ/", soundB: "/iː/", note: "Keep the jaw still on the short one.", noteVi: "Giữ hàm yên với âm ngắn." },
  { a: "full", b: "fool", soundA: "/ʊ/", soundB: "/uː/", note: "Round the lips more for the long sound.", noteVi: "Tròn môi hơn cho âm dài." },
  { a: "cat", b: "cut", soundA: "/æ/", soundB: "/ʌ/", note: "Wide mouth vs relaxed centre.", noteVi: "Miệng rộng so với thư giãn ở giữa." },
  { a: "bad", b: "bed", soundA: "/æ/", soundB: "/e/", note: "Drop the jaw further for bad.", noteVi: "Hạ hàm nhiều hơn với 'bad'." },
  { a: "think", b: "sink", soundA: "/θ/", soundB: "/s/", note: "Tongue between teeth vs behind teeth.", noteVi: "Lưỡi giữa răng so với sau răng." },
  { a: "very", b: "berry", soundA: "/v/", soundB: "/b/", note: "Teeth on lip vs lips together.", noteVi: "Răng trên môi so với hai môi chạm nhau." },
  { a: "light", b: "right", soundA: "/l/", soundB: "/r/", note: "Tongue touches vs tongue curls.", noteVi: "Lưỡi chạm so với lưỡi cuộn." },
];

export const STRESS_DRILLS = [
  { label: "Word stress", items: ["PHO-to-graph", "pho-TO-gra-pher", "pho-to-GRAPH-ic"], hint: "Same root, three stress patterns." },
  { label: "Sentence stress", items: ["I NEVER said she stole it.", "I never SAID she stole it.", "I never said SHE stole it."], hint: "Stress changes the meaning." },
  { label: "Intonation", items: ["You're coming. ↘", "You're coming? ↗", "You're coming?! ↗↘"], hint: "Pitch carries the attitude." },
  { label: "Connected speech", items: ["What are you doing? → Whatcha doin'?", "I want to go → I wanna go", "Did you eat? → Dija eat?"], hint: "Native speakers link and reduce." },
];

export const CONVERSATION_TOPICS = [
  "Daily Life",
  "Family",
  "Friends",
  "Work",
  "School",
  "Travel",
  "Food",
  "Shopping",
  "Hobbies",
  "Health",
  "Business",
  "Social Situations",
  "Free Conversation",
];

export const VOCAB_CATEGORIES = [
  "Everyday English",
  "Family",
  "Food & Drinks",
  "Shopping",
  "Travel",
  "Work & Office",
  "School",
  "Health",
  "Business English",
  "Customer Service",
  "Technology",
  "Relationships",
  "Hobbies",
  "Phrasal Verbs",
  "Idioms",
  "Commonly Confused Words",
  "IELTS Vocabulary",
  "TOEIC Vocabulary",
];
