/**
 * Full lesson content for the 44 English sounds — server-only on purpose.
 *
 * This array used to live in pronunciation-content.ts, which client routes
 * import for types/SKILLS/PRACTICE_STEPS; because pronunciation.tsx also
 * imported `SOUND_COUNT = PHONEMES.length`, the whole array (every locked
 * sound's how-to, mouth positions, words, sentences and minimal pairs) was
 * bundled into /assets/pronunciation-content-*.js and readable by anyone,
 * regardless of plan — verified on production 2026-09-16. The `.server.ts`
 * suffix keeps it out of the client graph by construction: the only way a
 * learner receives this content now is getSoundsCatalogue, which redacts
 * locked sounds (Yêu cầu 5, Yêu cầu 10).
 */
import type { Phoneme } from "./pronunciation-content";

export const PHONEMES: Phoneme[] = [
  /* ------------------------------ short vowels ----------------------------- */
  {
    symbol: "/ɪ/",
    name: "short i",
    group: "short-vowel",
    voiced: true,
    level: "beginner",
    difficulty: "medium",
    how: "Say a very short, relaxed 'i'. Do not smile and do not stretch it.",
    lips: "Relaxed, slightly apart — no smile.",
    teeth: "Teeth apart, no contact.",
    tongue: "High but pulled back towards the centre, loose.",
    jaw: "Almost closed, still.",
    mistakes: [
      "Stretching it into /iː/, so 'ship' becomes 'sheep'.",
      "Adding a smile, which lengthens the vowel.",
    ],
    words: [
      { word: "ship", sentence: "The ship sailed into the harbor." },
      { word: "sit", sentence: "Please sit down and relax." },
      { word: "bit", sentence: "She ate just a bit of cake." },
      { word: "live", sentence: "They live in a small town." },
      { word: "rich", sentence: "He became rich after the deal." },
      { word: "minute", sentence: "Wait just a minute, please." },
    ],
    sentences: ["This little kid is sitting still.", "It is a big fish in a little dish."],
    pairs: [
      { contrast: "/ɪ/ vs /iː/", a: "ship", b: "sheep", note: "Short and loose vs long and smiling." },
      { contrast: "/ɪ/ vs /iː/", a: "live", b: "leave", note: "Length changes the meaning completely." },
      { contrast: "/ɪ/ vs /e/", a: "bit", b: "bet", note: "Tongue drops a little for /e/." },
    ],
  },
  {
    symbol: "/e/",
    name: "short e",
    group: "short-vowel",
    voiced: true,
    level: "beginner",
    difficulty: "easy",
    how: "Mouth slightly open, say a crisp short 'e' as in 'bed'.",
    lips: "Neutral, spread a little.",
    teeth: "Comfortably apart.",
    tongue: "Mid-high and forward.",
    jaw: "Half closed.",
    mistakes: ["Opening too wide so 'bed' sounds like 'bad'.", "Adding a glide: 'bed' → 'beyd'."],
    words: [
      { word: "bed", sentence: "I go to bed at ten." },
      { word: "ten", sentence: "The bus leaves at ten o'clock." },
      { word: "head", sentence: "She hurt her head on the shelf." },
      { word: "said", sentence: "He said he would call later." },
      { word: "friend", sentence: "My best friend lives next door." },
      { word: "many", sentence: "There are many people here today." },
    ],
    sentences: ["Ten red pens are on the desk.", "My best friend said yes."],
    pairs: [
      { contrast: "/e/ vs /æ/", a: "bed", b: "bad", note: "Drop the jaw further for /æ/." },
      { contrast: "/e/ vs /ɪ/", a: "pen", b: "pin", note: "Very common confusion — keep /e/ more open." },
    ],
  },
  {
    symbol: "/æ/",
    name: "short a",
    group: "short-vowel",
    voiced: true,
    level: "beginner",
    difficulty: "medium",
    how: "Open wide and spread the lips, like a flat, bright 'a'.",
    lips: "Spread sideways.",
    teeth: "Wide apart.",
    tongue: "Low and forward.",
    jaw: "Clearly dropped.",
    mistakes: [
      "Using a Vietnamese 'e' so 'cat' sounds like 'ket'.",
      "Not opening the jaw, so 'bad' and 'bed' sound identical.",
    ],
    words: [
      { word: "cat", sentence: "The cat jumped onto the sofa." },
      { word: "bad", sentence: "That was a bad decision." },
      { word: "man", sentence: "The man greeted us warmly." },
      { word: "happy", sentence: "We were happy to see them." },
      { word: "answer", sentence: "I don't know the answer." },
      { word: "travel", sentence: "We love to travel every summer." },
    ],
    sentences: ["That cat sat on a black mat.", "Sam has a bad habit."],
    pairs: [
      { contrast: "/æ/ vs /e/", a: "bad", b: "bed", note: "Wider mouth for /æ/." },
      { contrast: "/æ/ vs /ʌ/", a: "cat", b: "cut", note: "Wide and bright vs relaxed and central." },
    ],
  },
  {
    symbol: "/ʌ/",
    name: "short u",
    group: "short-vowel",
    voiced: true,
    level: "beginner",
    difficulty: "medium",
    how: "Relax everything and make a short, punchy 'uh'.",
    lips: "Neutral, not rounded.",
    teeth: "Slightly apart.",
    tongue: "Central and low, completely relaxed.",
    jaw: "Half open.",
    mistakes: ["Rounding the lips so 'cut' sounds like 'cot'.", "Making it long — /ʌ/ is always short."],
    words: [
      { word: "cut", sentence: "He cut the paper in half." },
      { word: "bus", sentence: "We took the bus to school." },
      { word: "love", sentence: "They love spending time outdoors." },
      { word: "much", sentence: "Thank you so much for coming." },
      { word: "money", sentence: "She saved a lot of money." },
      { word: "brother", sentence: "My brother works in the city." },
    ],
    sentences: ["My brother loves running.", "Just one cup of coffee."],
    pairs: [
      { contrast: "/ʌ/ vs /ɒ/", a: "cut", b: "cot", note: "No lip rounding on /ʌ/." },
      { contrast: "/ʌ/ vs /æ/", a: "cup", b: "cap", note: "Central vs wide and bright." },
    ],
  },
  {
    symbol: "/ɒ/",
    usSymbol: "/ɑ/",
    name: "short o",
    group: "short-vowel",
    voiced: true,
    level: "intermediate",
    difficulty: "hard",
    how: "Round the lips a little and say a short, open 'o'.",
    lips: "Lightly rounded.",
    teeth: "Well apart.",
    tongue: "Low and back.",
    jaw: "Open.",
    mistakes: [
      "Using the long /ɔː/ so 'not' sounds like 'naught'.",
      "Mixing accents: British 'hot' uses /ɒ/, American 'hot' uses /ɑ/.",
    ],
    words: [
      { word: "hot", sentence: "The soup is too hot." },
      { word: "not", sentence: "This is not my bag." },
      { word: "stop", sentence: "The train made a short stop." },
      { word: "job", sentence: "He starts his new job tomorrow." },
      { word: "watch", sentence: "I like to watch the sunset." },
      { word: "possible", sentence: "It is possible to finish today." },
    ],
    sentences: ["The clock stopped on top of the box.", "It is not a hot job."],
    pairs: [
      { contrast: "/ɒ/ vs /ɔː/", a: "not", b: "nought", note: "Short vs long, same lip shape." },
      { contrast: "/ɒ/ vs /ʌ/", a: "cot", b: "cut", note: "Rounded vs neutral lips." },
    ],
    accentNote: "British English uses /ɒ/. American English usually uses an unrounded /ɑ/ in the same words.",
  },
  {
    symbol: "/ʊ/",
    name: "short oo",
    group: "short-vowel",
    voiced: true,
    level: "beginner",
    difficulty: "medium",
    how: "Very short, loose 'u' with barely rounded lips.",
    lips: "Slightly rounded, relaxed.",
    teeth: "Close together.",
    tongue: "High-back but pulled towards the centre.",
    jaw: "Nearly closed.",
    mistakes: ["Stretching it into /uː/, so 'full' becomes 'fool'.", "Rounding the lips too tightly."],
    words: [
      { word: "book", sentence: "He wrote a book last year." },
      { word: "good", sentence: "He is a good friend." },
      { word: "put", sentence: "Please put the box down." },
      { word: "full", sentence: "The bus was completely full." },
      { word: "could", sentence: "He could not find his keys." },
      { word: "woman", sentence: "The woman smiled at the baby." },
    ],
    sentences: ["Put the good book down.", "She could not look."],
    pairs: [
      { contrast: "/ʊ/ vs /uː/", a: "full", b: "fool", note: "Short and loose vs long and tight." },
      { contrast: "/ʊ/ vs /ʌ/", a: "look", b: "luck", note: "Rounded vs neutral." },
    ],
  },
  {
    symbol: "/ə/",
    name: "schwa",
    group: "short-vowel",
    voiced: true,
    level: "beginner",
    difficulty: "medium",
    how: "The laziest English sound: relax completely and say a tiny 'uh'.",
    lips: "Fully relaxed, barely open.",
    teeth: "Slightly apart.",
    tongue: "Resting in the middle of the mouth.",
    jaw: "Almost closed and still.",
    mistakes: [
      "Pronouncing every letter fully, so 'banana' becomes 'ba-na-na' instead of /bəˈnɑːnə/.",
      "Stressing a schwa syllable — schwa is never stressed.",
    ],
    words: [
      { word: "about", sentence: "Tell me about your day." },
      { word: "teacher", sentence: "Our teacher explained it clearly." },
      { word: "banana", sentence: "She ate a banana for breakfast." },
      { word: "support", sentence: "Thank you for your support." },
      { word: "police", sentence: "The police arrived quickly." },
      { word: "problem", sentence: "There is no problem at all." },
    ],
    sentences: ["A banana for the teacher.", "The police support the doctor."],
    pairs: [
      { contrast: "/ə/ vs /ʌ/", a: "aBOUT", b: "but", note: "Schwa is unstressed; /ʌ/ carries stress." },
      { contrast: "/ə/ vs /ɜː/", a: "forWARD", b: "word", note: "Schwa is short, /ɜː/ is long and stressed." },
    ],
  },

  /* ------------------------------ long vowels ------------------------------ */
  {
    symbol: "/iː/",
    name: "long ee",
    group: "long-vowel",
    voiced: true,
    level: "beginner",
    difficulty: "easy",
    how: "Smile and hold a long 'ee'.",
    lips: "Spread wide, almost smiling.",
    teeth: "Close together.",
    tongue: "High and far forward.",
    jaw: "Nearly closed.",
    mistakes: ["Cutting it short so 'sheep' becomes 'ship'.", "Forgetting the smile, which shortens the sound."],
    words: [
      { word: "sheep", sentence: "The sheep grazed in the field." },
      { word: "seat", sentence: "Please take a seat here." },
      { word: "leave", sentence: "We will leave at noon." },
      { word: "green", sentence: "The leaves turned bright green." },
      { word: "people", sentence: "Some people arrived late." },
      { word: "believe", sentence: "I can't believe the news." },
    ],
    sentences: ["She needs a clean sheet of paper.", "Three green trees."],
    pairs: [
      { contrast: "/iː/ vs /ɪ/", a: "seat", b: "sit", note: "Long and smiling vs short and loose." },
      { contrast: "/iː/ vs /ɪ/", a: "feel", b: "fill", note: "Hold the vowel twice as long." },
    ],
  },
  {
    symbol: "/ɑː/",
    name: "long ah",
    group: "long-vowel",
    voiced: true,
    level: "intermediate",
    difficulty: "medium",
    how: "Open your mouth like at the dentist and hold a long 'ah'.",
    lips: "Neutral, not rounded.",
    teeth: "Wide apart.",
    tongue: "Low and back.",
    jaw: "Fully dropped.",
    mistakes: ["Making it short like /ʌ/.", "Adding an /r/ in British English words such as 'car'."],
    words: [
      { word: "car", sentence: "He parked the car outside." },
      { word: "far", sentence: "The station is not far away." },
      { word: "father", sentence: "My father works at a bank." },
      { word: "start", sentence: "Let's start the meeting now." },
      { word: "heart", sentence: "Her heart was full of joy." },
      { word: "calm", sentence: "The sea was calm this morning." },
    ],
    sentences: ["Father parked the car far away.", "Start the car after dark."],
    pairs: [
      { contrast: "/ɑː/ vs /ʌ/", a: "cart", b: "cut", note: "Long and open vs short and central." },
      { contrast: "/ɑː/ vs /æ/", a: "calm", b: "cam", note: "Back and long vs front and bright." },
    ],
    accentNote: "In American English the /r/ in 'car' and 'start' is pronounced; in British RP it is silent.",
  },
  {
    symbol: "/ɔː/",
    name: "long aw",
    group: "long-vowel",
    voiced: true,
    level: "intermediate",
    difficulty: "medium",
    how: "Round the lips and hold a long 'aw'.",
    lips: "Clearly rounded and pushed forward.",
    teeth: "Fairly apart.",
    tongue: "Low and back.",
    jaw: "Open.",
    mistakes: ["Shortening it to /ɒ/.", "Losing the lip rounding halfway through."],
    words: [
      { word: "thought", sentence: "I thought you were coming too." },
      { word: "law", sentence: "She studies law at university." },
      { word: "caught", sentence: "He caught the ball easily." },
      { word: "door", sentence: "Please close the door quietly." },
      { word: "before", sentence: "I have seen this movie before." },
      { word: "always", sentence: "He always arrives early." },
    ],
    sentences: ["He bought a tall door.", "I always thought so."],
    pairs: [
      { contrast: "/ɔː/ vs /ɒ/", a: "caught", b: "cot", note: "Long vs short." },
      { contrast: "/ɔː/ vs /əʊ/", a: "law", b: "low", note: "Steady vowel vs gliding diphthong." },
    ],
  },
  {
    symbol: "/uː/",
    name: "long oo",
    group: "long-vowel",
    voiced: true,
    level: "beginner",
    difficulty: "easy",
    how: "Push the lips forward into a small circle and hold 'oo'.",
    lips: "Tightly rounded, pushed forward.",
    teeth: "Close together.",
    tongue: "High and back.",
    jaw: "Nearly closed.",
    mistakes: ["Cutting it short so 'fool' becomes 'full'.", "Not rounding the lips enough."],
    words: [
      { word: "food", sentence: "The food smelled delicious." },
      { word: "blue", sentence: "The sky turned deep blue." },
      { word: "true", sentence: "Is this story actually true?" },
      { word: "school", sentence: "My children go to school nearby." },
      { word: "choose", sentence: "You can choose any color." },
      { word: "usually", sentence: "I usually walk to work." },
    ],
    sentences: ["Two blue shoes.", "Who chose the new food?"],
    pairs: [
      { contrast: "/uː/ vs /ʊ/", a: "fool", b: "full", note: "Long and tight vs short and loose." },
      { contrast: "/uː/ vs /juː/", a: "food", b: "feud", note: "Some words add a /j/ glide first." },
    ],
  },
  {
    symbol: "/ɜː/",
    usSymbol: "/ɝ/",
    name: "long er",
    group: "long-vowel",
    voiced: true,
    level: "intermediate",
    difficulty: "hard",
    how: "Hold a long, neutral 'er' with the tongue slightly curled.",
    lips: "Slightly rounded, jaw mid.",
    teeth: "Apart.",
    tongue: "Central; the tip curls a little back without touching anything.",
    jaw: "Mid open.",
    mistakes: [
      "Replacing it with a Vietnamese 'ơ' that is too short.",
      "Dropping the r-colour in American English words such as 'work'.",
    ],
    words: [
      { word: "bird", sentence: "A small bird sang outside." },
      { word: "work", sentence: "She walks to work every day." },
      { word: "learn", sentence: "We learn something new every day." },
      { word: "nurse", sentence: "The nurse checked his temperature." },
      { word: "first", sentence: "This is my first visit here." },
      { word: "person", sentence: "He is a very kind person." },
    ],
    sentences: ["The nurse learned first.", "Her first word was perfect."],
    pairs: [
      { contrast: "/ɜː/ vs /ə/", a: "bird", b: "about", note: "Long and stressed vs short and unstressed." },
      { contrast: "/ɜː/ vs /ɔː/", a: "were", b: "war", note: "Neutral vs rounded." },
    ],
    accentNote: "American English keeps a strong r-colour (/ɝ/); British RP has no audible r at the end.",
  },

  /* ------------------------------- diphthongs ------------------------------ */
  {
    symbol: "/eɪ/",
    name: "ay diphthong",
    group: "diphthong",
    voiced: true,
    level: "beginner",
    difficulty: "easy",
    how: "Start at /e/ and glide up into /ɪ/ — one smooth movement.",
    lips: "Start neutral, finish spread.",
    teeth: "Apart, closing slightly.",
    tongue: "Moves from mid-front up to high-front.",
    jaw: "Half open, then closing.",
    mistakes: ["Saying a flat /e/ with no glide, so 'late' sounds like 'let'.", "Splitting it into two syllables."],
    words: [
      { word: "day", sentence: "It was a long day at work." },
      { word: "make", sentence: "Let's make dinner together." },
      { word: "rain", sentence: "The rain stopped after lunch." },
      { word: "eight", sentence: "The train leaves at eight." },
      { word: "later", sentence: "I will call you later." },
      { word: "afraid", sentence: "Don't be afraid of the dark." },
    ],
    sentences: ["They came late today.", "Wait — it may rain."],
    pairs: [
      { contrast: "/eɪ/ vs /e/", a: "late", b: "let", note: "Glide up for /eɪ/." },
      { contrast: "/eɪ/ vs /aɪ/", a: "pain", b: "pine", note: "Start position changes." },
    ],
  },
  {
    symbol: "/aɪ/",
    name: "eye diphthong",
    group: "diphthong",
    voiced: true,
    level: "beginner",
    difficulty: "easy",
    how: "Open wide, then glide up towards a smile.",
    lips: "Open, then spreading.",
    teeth: "Wide, then closing.",
    tongue: "Low-front gliding to high-front.",
    jaw: "Dropped, then closing.",
    mistakes: ["Cutting the glide short.", "Making it two separate syllables."],
    words: [
      { word: "time", sentence: "Take your time to decide." },
      { word: "my", sentence: "This is my favorite book." },
      { word: "five", sentence: "We waited for five minutes." },
      { word: "night", sentence: "The stars shone brightly at night." },
      { word: "decide", sentence: "We need to decide quickly." },
      { word: "quiet", sentence: "The library was completely quiet." },
    ],
    sentences: ["Five nights of my life.", "I like this quiet time."],
    pairs: [
      { contrast: "/aɪ/ vs /ɔɪ/", a: "file", b: "foil", note: "Start unrounded vs rounded." },
      { contrast: "/aɪ/ vs /eɪ/", a: "might", b: "mate", note: "Wide start vs mid start." },
    ],
  },
  {
    symbol: "/ɔɪ/",
    name: "oy diphthong",
    group: "diphthong",
    voiced: true,
    level: "intermediate",
    difficulty: "easy",
    how: "Start with rounded 'aw', then glide to 'ee'.",
    lips: "Rounded, then spreading.",
    teeth: "Apart, then closing.",
    tongue: "Back-low gliding to front-high.",
    jaw: "Open, then closing.",
    mistakes: ["Losing the rounded start.", "Stopping halfway so 'boy' sounds like 'baw'."],
    words: [
      { word: "boy", sentence: "The boy played in the park." },
      { word: "noise", sentence: "There was a loud noise outside." },
      { word: "choice", sentence: "You made a wise choice." },
      { word: "enjoy", sentence: "I really enjoy this music." },
      { word: "point", sentence: "That is a good point." },
      { word: "avoid", sentence: "Try to avoid busy roads." },
    ],
    sentences: ["The boys enjoy the noise.", "Avoid that choice."],
    pairs: [
      { contrast: "/ɔɪ/ vs /aɪ/", a: "boil", b: "bile", note: "Rounded vs unrounded start." },
      { contrast: "/ɔɪ/ vs /ɔː/", a: "coin", b: "corn", note: "Glide vs steady vowel." },
    ],
  },
  {
    symbol: "/əʊ/",
    usSymbol: "/oʊ/",
    name: "oh diphthong",
    group: "diphthong",
    voiced: true,
    level: "beginner",
    difficulty: "medium",
    how: "Start neutral and round the lips as you finish.",
    lips: "Neutral, then rounded.",
    teeth: "Apart, then closing.",
    tongue: "Central gliding back and up.",
    jaw: "Mid, then closing.",
    mistakes: [
      "Saying a flat Vietnamese 'ô' with no glide.",
      "Mixing accents — British starts with /ə/, American starts with /o/.",
    ],
    words: [
      { word: "go", sentence: "It's time to go to bed." },
      { word: "boat", sentence: "They sailed the boat across the lake." },
      { word: "know", sentence: "Do you know the way home?" },
      { word: "phone", sentence: "She left her phone at home." },
      { word: "hope", sentence: "I hope you feel better soon." },
      { word: "although", sentence: "Although it rained, we stayed outside." },
    ],
    sentences: ["I know the old road home.", "Don't go alone."],
    pairs: [
      { contrast: "/əʊ/ vs /ɔː/", a: "coat", b: "caught", note: "Glide vs steady." },
      { contrast: "/əʊ/ vs /ʌ/", a: "boat", b: "but", note: "Long glide vs short punch." },
    ],
    accentNote: "British RP writes this /əʊ/, American English /oʊ/ — the American start is more rounded.",
  },
  {
    symbol: "/aʊ/",
    name: "ow diphthong",
    group: "diphthong",
    voiced: true,
    level: "beginner",
    difficulty: "easy",
    how: "Open wide, then round the lips as you glide to 'oo'.",
    lips: "Open, then rounded.",
    teeth: "Wide, then closing.",
    tongue: "Low-front gliding high-back.",
    jaw: "Dropped, then closing.",
    mistakes: ["Not rounding at the end.", "Making it too short."],
    words: [
      { word: "now", sentence: "We should leave right now." },
      { word: "house", sentence: "Their house is near the park." },
      { word: "around", sentence: "We looked around the museum." },
      { word: "loud", sentence: "The music was too loud." },
      { word: "down", sentence: "Please sit down for a moment." },
      { word: "about", sentence: "Tell me about your day." },
    ],
    sentences: ["How about now?", "The loud crowd went downtown."],
    pairs: [
      { contrast: "/aʊ/ vs /əʊ/", a: "town", b: "tone", note: "Wide start vs neutral start." },
      { contrast: "/aʊ/ vs /ɑː/", a: "loud", b: "lard", note: "Glide vs steady." },
    ],
  },
  {
    symbol: "/ɪə/",
    usSymbol: "/ɪr/",
    name: "ear diphthong",
    group: "diphthong",
    voiced: true,
    level: "intermediate",
    difficulty: "medium",
    how: "Say /ɪ/ and relax into a schwa.",
    lips: "Relaxed throughout.",
    teeth: "Slightly apart.",
    tongue: "High-front sliding to centre.",
    jaw: "Nearly closed, opening slightly.",
    mistakes: ["Making one flat vowel.", "Adding a hard /r/ in British English."],
    words: [
      { word: "here", sentence: "Come and sit here with us." },
      { word: "near", sentence: "The shop is near my house." },
      { word: "clear", sentence: "The instructions were very clear." },
      { word: "really", sentence: "I really enjoyed the movie." },
      { word: "idea", sentence: "That's a great idea." },
      { word: "career", sentence: "She started a new career." },
    ],
    sentences: ["Come here — it is clear and near.", "That idea is really clear."],
    pairs: [
      { contrast: "/ɪə/ vs /iː/", a: "beer", b: "bee", note: "Glide to schwa vs steady long vowel." },
      { contrast: "/ɪə/ vs /eə/", a: "beer", b: "bear", note: "Start high vs start mid." },
    ],
    accentNote: "American English pronounces the r: 'here' /hɪr/. British RP glides into a schwa instead.",
  },
  {
    symbol: "/eə/",
    usSymbol: "/er/",
    name: "air diphthong",
    group: "diphthong",
    voiced: true,
    level: "intermediate",
    difficulty: "medium",
    how: "Say /e/ and relax into a schwa.",
    lips: "Neutral.",
    teeth: "Apart.",
    tongue: "Mid-front sliding to centre.",
    jaw: "Half open.",
    mistakes: ["Using /iː/ instead of /e/ at the start.", "Cutting the schwa off."],
    words: [
      { word: "air", sentence: "The mountain air felt fresh." },
      { word: "care", sentence: "Take care on your trip." },
      { word: "where", sentence: "Where did you put my keys?" },
      { word: "hair", sentence: "She cut her hair short." },
      { word: "compare", sentence: "Let's compare the two options." },
      { word: "prepare", sentence: "We need to prepare for the test." },
    ],
    sentences: ["Where is the fair hair care?", "Prepare and compare."],
    pairs: [
      { contrast: "/eə/ vs /ɪə/", a: "bear", b: "beer", note: "Mid start vs high start." },
      { contrast: "/eə/ vs /e/", a: "share", b: "shed", note: "Glide vs short vowel." },
    ],
    accentNote: "American English pronounces the r: 'care' /ker/.",
  },
  {
    symbol: "/ʊə/",
    usSymbol: "/ʊr/",
    name: "ure diphthong",
    group: "diphthong",
    voiced: true,
    level: "advanced",
    difficulty: "hard",
    how: "Say /ʊ/ and relax into a schwa.",
    lips: "Lightly rounded, then relaxing.",
    teeth: "Close, opening slightly.",
    tongue: "High-back sliding to centre.",
    jaw: "Nearly closed.",
    mistakes: ["Replacing it with /ɔː/ (common even for natives in 'sure').", "Losing the rounded start."],
    words: [
      { word: "tour", sentence: "We took a tour of the city." },
      { word: "poor", sentence: "The family was very poor." },
      { word: "sure", sentence: "I am sure about my decision." },
      { word: "cure", sentence: "Scientists searched for a cure." },
      { word: "pure", sentence: "The water here is pure." },
      { word: "mature", sentence: "He seems mature for his age." },
    ],
    sentences: ["Are you sure about the tour?", "A pure cure for the poor."],
    pairs: [
      { contrast: "/ʊə/ vs /ɔː/", a: "poor", b: "pour", note: "Many speakers merge these — practise both." },
      { contrast: "/ʊə/ vs /uː/", a: "tour", b: "too", note: "Glide vs steady long vowel." },
    ],
    accentNote: "Both British and American speakers often replace /ʊə/ with /ɔː/ or /ʊr/ — say which one you are copying.",
  },

  /* -------------------------------- plosives ------------------------------- */
  {
    symbol: "/p/",
    name: "p",
    group: "plosive",
    voiced: false,
    level: "beginner",
    difficulty: "easy",
    how: "Close both lips, build air, then release a small puff — no voice.",
    lips: "Pressed together, then released.",
    teeth: "Not involved.",
    tongue: "Neutral.",
    jaw: "Closed, then opening.",
    mistakes: [
      "No puff of air at the start of a word: 'pen' sounds like 'ben'.",
      "Dropping the final /p/ in 'stop' or 'help'.",
    ],
    words: [
      { word: "pen", sentence: "Can I borrow your pen?" },
      { word: "happy", sentence: "We were happy to see them." },
      { word: "stop", sentence: "The train made a short stop." },
      { word: "people", sentence: "Some people arrived late." },
      { word: "apple", sentence: "She picked a red apple." },
      { word: "help", sentence: "Can you help me with this?" },
    ],
    sentences: ["Peter put the paper in his pocket.", "Please stop pushing."],
    pairs: [
      { contrast: "/p/ vs /b/", a: "pen", b: "Ben", note: "Voiceless with a puff vs voiced." },
      { contrast: "/p/ vs /f/", a: "pan", b: "fan", note: "Full lip closure vs teeth on lip." },
    ],
  },
  {
    symbol: "/b/",
    name: "b",
    group: "plosive",
    voiced: true,
    level: "beginner",
    difficulty: "easy",
    how: "Same as /p/ but with the voice buzzing and no strong puff.",
    lips: "Pressed together, then released.",
    teeth: "Not involved.",
    tongue: "Neutral.",
    jaw: "Closed, then opening.",
    mistakes: ["Dropping the final /b/ in 'job' or 'club'.", "Devoicing it so 'big' sounds like 'pig'."],
    words: [
      { word: "big", sentence: "That is a big surprise." },
      { word: "baby", sentence: "The baby slept peacefully." },
      { word: "job", sentence: "He starts his new job tomorrow." },
      { word: "about", sentence: "Tell me about your day." },
      { word: "club", sentence: "We joined a chess club." },
      { word: "problem", sentence: "There is no problem at all." },
    ],
    sentences: ["The baby is a bit busy.", "Bob booked a big cab."],
    pairs: [
      { contrast: "/b/ vs /p/", a: "bat", b: "pat", note: "Voiced vs voiceless." },
      { contrast: "/b/ vs /v/", a: "berry", b: "very", note: "Lips together vs teeth on lip." },
    ],
  },
  {
    symbol: "/t/",
    name: "t",
    group: "plosive",
    voiced: false,
    level: "beginner",
    difficulty: "easy",
    how: "Tongue tip taps the ridge behind the top teeth, release air — no voice.",
    lips: "Relaxed.",
    teeth: "Slightly apart.",
    tongue: "Tip on the ridge behind the upper teeth.",
    jaw: "Nearly closed.",
    mistakes: [
      "Leaving the final /t/ out: 'want' → 'wan'.",
      "Using a Vietnamese unreleased /t/ at the end of every word.",
    ],
    words: [
      { word: "time", sentence: "Take your time to decide." },
      { word: "water", sentence: "Please drink more water." },
      { word: "want", sentence: "What do you want to eat?" },
      { word: "sit", sentence: "Please sit down and relax." },
      { word: "better", sentence: "I feel much better today." },
      { word: "important", sentence: "This meeting is very important." },
    ],
    sentences: ["Take the time to talk to Tom.", "It is important to try."],
    pairs: [
      { contrast: "/t/ vs /d/", a: "time", b: "dime", note: "Voiceless vs voiced." },
      { contrast: "/t/ vs /θ/", a: "tin", b: "thin", note: "Tongue on ridge vs between teeth." },
    ],
    accentNote: "American English often taps /t/ between vowels: 'water' sounds close to 'wader'.",
  },
  {
    symbol: "/d/",
    name: "d",
    group: "plosive",
    voiced: true,
    level: "beginner",
    difficulty: "easy",
    how: "Same place as /t/ but with the voice on.",
    lips: "Relaxed.",
    teeth: "Slightly apart.",
    tongue: "Tip on the ridge behind the upper teeth.",
    jaw: "Nearly closed.",
    mistakes: ["Dropping the final /d/ in 'need' or 'good'.", "Turning /d/ into /t/ at the end of words."],
    words: [
      { word: "day", sentence: "It was a long day at work." },
      { word: "did", sentence: "She did very well on the test." },
      { word: "need", sentence: "We need more time to finish." },
      { word: "good", sentence: "He is a good friend." },
      { word: "under", sentence: "The cat hid under the table." },
      { word: "decided", sentence: "They decided to move abroad." },
    ],
    sentences: ["Dad did it during the day.", "I decided I needed a doctor."],
    pairs: [
      { contrast: "/d/ vs /t/", a: "bed", b: "bet", note: "Voiced vs voiceless ending." },
      { contrast: "/d/ vs /ð/", a: "dare", b: "there", note: "Ridge stop vs soft buzz between teeth." },
    ],
  },
  {
    symbol: "/k/",
    name: "k",
    group: "plosive",
    voiced: false,
    level: "beginner",
    difficulty: "easy",
    how: "Back of the tongue blocks the throat, then release a puff — no voice.",
    lips: "Relaxed.",
    teeth: "Apart.",
    tongue: "Back rises to the soft palate.",
    jaw: "Half open.",
    mistakes: ["No release at the end: 'book' loses its /k/.", "Swapping with /ɡ/."],
    words: [
      { word: "cat", sentence: "The cat jumped onto the sofa." },
      { word: "school", sentence: "My children go to school nearby." },
      { word: "book", sentence: "He wrote a book last year." },
      { word: "quick", sentence: "It was a quick decision." },
      { word: "because", sentence: "She smiled because she was happy." },
      { word: "market", sentence: "We buy vegetables at the market." },
    ],
    sentences: ["Can you keep the key?", "I took a quick look at the book."],
    pairs: [
      { contrast: "/k/ vs /ɡ/", a: "coat", b: "goat", note: "Voiceless vs voiced." },
      { contrast: "/k/ vs /h/", a: "cat", b: "hat", note: "Full stop vs free airflow." },
    ],
  },
  {
    symbol: "/ɡ/",
    name: "g",
    group: "plosive",
    voiced: true,
    level: "beginner",
    difficulty: "easy",
    how: "Same as /k/ with the voice buzzing.",
    lips: "Relaxed.",
    teeth: "Apart.",
    tongue: "Back against the soft palate.",
    jaw: "Half open.",
    mistakes: ["Devoicing so 'bag' sounds like 'back'.", "Adding an extra vowel: 'big' → 'bi-gə'."],
    words: [
      { word: "go", sentence: "It's time to go to bed." },
      { word: "big", sentence: "That is a big surprise." },
      { word: "again", sentence: "Please explain that again." },
      { word: "bag", sentence: "She carried a heavy bag." },
      { word: "forget", sentence: "Don't forget your umbrella." },
      { word: "language", sentence: "Learning a new language takes time." },
    ],
    sentences: ["The girl got a big bag.", "Let's go again."],
    pairs: [
      { contrast: "/ɡ/ vs /k/", a: "bag", b: "back", note: "Keep the voice on for /ɡ/." },
      { contrast: "/ɡ/ vs /dʒ/", a: "gay", b: "jay", note: "Back stop vs front affricate." },
    ],
  },

  /* ------------------------------- fricatives ------------------------------ */
  {
    symbol: "/f/",
    name: "f",
    group: "fricative",
    voiced: false,
    level: "beginner",
    difficulty: "easy",
    how: "Top teeth touch the lower lip and blow steadily — no voice.",
    lips: "Lower lip under the upper teeth.",
    teeth: "Upper teeth on the lip.",
    tongue: "Not involved.",
    jaw: "Nearly closed.",
    mistakes: ["Using /p/ instead of /f/.", "Dropping the final /f/ in 'life'."],
    words: [
      { word: "fun", sentence: "We had so much fun today." },
      { word: "coffee", sentence: "He drinks coffee every morning." },
      { word: "life", sentence: "City life can be exciting." },
      { word: "before", sentence: "I have seen this movie before." },
      { word: "different", sentence: "This recipe tastes different." },
      { word: "enough", sentence: "We don't have enough time." },
    ],
    sentences: ["Find four fresh coffees.", "Life is different for my family."],
    pairs: [
      { contrast: "/f/ vs /v/", a: "fan", b: "van", note: "Voiceless vs voiced, same position." },
      { contrast: "/f/ vs /p/", a: "fine", b: "pine", note: "Continuous air vs sudden release." },
    ],
  },
  {
    symbol: "/v/",
    name: "v",
    group: "fricative",
    voiced: true,
    level: "beginner",
    difficulty: "hard",
    how: "Same as /f/ but let the voice buzz through.",
    lips: "Lower lip under the upper teeth.",
    teeth: "Upper teeth on the lip.",
    tongue: "Not involved.",
    jaw: "Nearly closed.",
    mistakes: [
      "Using a Vietnamese 'v' made with both lips, which sounds like /b/ or /w/.",
      "Devoicing so 'have' sounds like 'half'.",
    ],
    words: [
      { word: "very", sentence: "The soup was very tasty." },
      { word: "love", sentence: "They love spending time outdoors." },
      { word: "believe", sentence: "I can't believe the news." },
      { word: "voice", sentence: "His voice was calm and clear." },
      { word: "over", sentence: "The game is finally over." },
      { word: "seven", sentence: "We meet every day at seven." },
    ],
    sentences: ["Very lovely voice.", "I believe I have seven."],
    pairs: [
      { contrast: "/v/ vs /b/", a: "very", b: "berry", note: "Teeth on lip vs lips together." },
      { contrast: "/v/ vs /w/", a: "vine", b: "wine", note: "Teeth contact vs rounded lips only." },
    ],
  },
  {
    symbol: "/θ/",
    name: "voiceless th",
    group: "fricative",
    voiced: false,
    level: "intermediate",
    difficulty: "hard",
    how: "Tongue tip lightly between the teeth, blow air — no voice.",
    lips: "Relaxed and open.",
    teeth: "Lightly holding the tongue tip.",
    tongue: "Tip just between or touching the upper teeth.",
    jaw: "Slightly open.",
    mistakes: [
      "Replacing it with /t/: 'think' → 'tink'.",
      "Replacing it with /s/: 'think' → 'sink'.",
      "Hiding the tongue behind the teeth.",
    ],
    words: [
      { word: "think", sentence: "I think you are right." },
      { word: "three", sentence: "We waited for three hours." },
      { word: "thank", sentence: "I want to thank you for your help." },
      { word: "mouth", sentence: "Cover your mouth when you cough." },
      { word: "healthy", sentence: "Eating vegetables keeps you healthy." },
      { word: "something", sentence: "I need to tell you something." },
    ],
    sentences: ["I think three things.", "Thank you for the healthy month."],
    pairs: [
      { contrast: "/θ/ vs /t/", a: "think", b: "tink", note: "Tongue between teeth vs on the ridge." },
      { contrast: "/θ/ vs /s/", a: "think", b: "sink", note: "Air over the tongue tip vs a sharp hiss." },
      { contrast: "/θ/ vs /f/", a: "three", b: "free", note: "Tongue vs lip." },
    ],
  },
  {
    symbol: "/ð/",
    name: "voiced th",
    group: "fricative",
    voiced: true,
    level: "intermediate",
    difficulty: "hard",
    how: "Same position as /θ/, but buzz with your voice.",
    lips: "Relaxed.",
    teeth: "Lightly on the tongue tip.",
    tongue: "Tip between the teeth, vibrating.",
    jaw: "Slightly open.",
    mistakes: ["Replacing it with /d/: 'this' → 'dis'.", "Replacing it with /z/: 'these' → 'zeez'."],
    words: [
      { word: "this", sentence: "This is my favorite place." },
      { word: "that", sentence: "That was an excellent idea." },
      { word: "mother", sentence: "Her mother called this morning." },
      { word: "weather", sentence: "The weather is lovely today." },
      { word: "another", sentence: "Let's try another approach." },
      { word: "together", sentence: "We cooked dinner together." },
    ],
    sentences: ["This is my mother.", "They are together in that weather."],
    pairs: [
      { contrast: "/ð/ vs /d/", a: "then", b: "den", note: "Soft buzz vs hard stop." },
      { contrast: "/ð/ vs /z/", a: "these", b: "zees", note: "Tongue out vs tongue behind the teeth." },
    ],
  },
  {
    symbol: "/s/",
    name: "s",
    group: "fricative",
    voiced: false,
    level: "beginner",
    difficulty: "easy",
    how: "Tongue near the ridge, blow a thin hiss — no voice.",
    lips: "Slightly spread.",
    teeth: "Almost together.",
    tongue: "Tip close to the ridge, groove in the middle.",
    jaw: "Nearly closed.",
    mistakes: ["Dropping /s/ in plurals and third-person verbs.", "Confusing it with /ʃ/."],
    words: [
      { word: "see", sentence: "I can see the mountains clearly." },
      { word: "class", sentence: "Our class starts at nine." },
      { word: "some", sentence: "Can I borrow some sugar?" },
      { word: "office", sentence: "She works at a busy office." },
      { word: "answers", sentence: "He wrote all the answers quickly." },
      { word: "outside", sentence: "The children played outside." },
    ],
    sentences: ["She sees six students.", "Sam speaks fast."],
    pairs: [
      { contrast: "/s/ vs /z/", a: "sip", b: "zip", note: "Voiceless vs voiced." },
      { contrast: "/s/ vs /ʃ/", a: "sea", b: "she", note: "Thin hiss vs wide, rounded hush." },
    ],
  },
  {
    symbol: "/z/",
    name: "z",
    group: "fricative",
    voiced: true,
    level: "beginner",
    difficulty: "medium",
    how: "Same as /s/ but with the voice buzzing.",
    lips: "Slightly spread.",
    teeth: "Almost together.",
    tongue: "Tip near the ridge.",
    jaw: "Nearly closed.",
    mistakes: [
      "Turning final /z/ into /s/: 'is' → 'iss'.",
      "Forgetting that most plural -s endings after voiced sounds are /z/.",
    ],
    words: [
      { word: "zoo", sentence: "We visited the zoo yesterday." },
      { word: "is", sentence: "This is my new phone." },
      { word: "busy", sentence: "The office was very busy today." },
      { word: "these", sentence: "These shoes are quite comfortable." },
      { word: "because", sentence: "She smiled because she was happy." },
      { word: "music", sentence: "They played soft music." },
    ],
    sentences: ["These lazy days are easy.", "He is busy because of music."],
    pairs: [
      { contrast: "/z/ vs /s/", a: "buzz", b: "bus", note: "Keep the voice on for /z/." },
      { contrast: "/z/ vs /dʒ/", a: "zip", b: "gyp", note: "Smooth buzz vs stop plus buzz." },
    ],
  },
  {
    symbol: "/ʃ/",
    name: "sh",
    group: "fricative",
    voiced: false,
    level: "beginner",
    difficulty: "easy",
    how: "Push the lips forward and hush — no voice.",
    lips: "Rounded and pushed forward.",
    teeth: "Close together.",
    tongue: "Broad and close to the roof, a little behind /s/.",
    jaw: "Nearly closed.",
    mistakes: ["Using /s/ instead.", "Forgetting the lip rounding."],
    words: [
      { word: "she", sentence: "She works as a doctor." },
      { word: "shop", sentence: "We went to the shop together." },
      { word: "fish", sentence: "They caught fresh fish at the lake." },
      { word: "nation", sentence: "The whole nation celebrated the win." },
      { word: "sure", sentence: "I am sure about my decision." },
      { word: "machine", sentence: "The machine stopped working suddenly." },
    ],
    sentences: ["She should shop for fresh fish.", "That station is sure to be shut."],
    pairs: [
      { contrast: "/ʃ/ vs /s/", a: "ship", b: "sip", note: "Rounded hush vs thin hiss." },
      { contrast: "/ʃ/ vs /tʃ/", a: "share", b: "chair", note: "Smooth air vs stop first." },
    ],
  },
  {
    symbol: "/ʒ/",
    name: "zh",
    group: "fricative",
    voiced: true,
    level: "advanced",
    difficulty: "hard",
    how: "Same as /ʃ/ but with the voice buzzing.",
    lips: "Rounded and forward.",
    teeth: "Close together.",
    tongue: "Broad, near the roof.",
    jaw: "Nearly closed.",
    mistakes: ["Replacing it with /dʒ/: 'measure' → 'mejure'.", "Devoicing it into /ʃ/."],
    words: [
      { word: "measure", sentence: "Please measure the table first." },
      { word: "usually", sentence: "I usually walk to work." },
      { word: "decision", sentence: "It was a difficult decision." },
      { word: "vision", sentence: "Her vision for the project was clear." },
      { word: "pleasure", sentence: "It was a pleasure to meet you." },
      { word: "garage", sentence: "He parked the car in the garage." },
    ],
    sentences: ["It is a pleasure to measure.", "Usually the decision is her vision."],
    pairs: [
      { contrast: "/ʒ/ vs /ʃ/", a: "measure", b: "mesher", note: "Voiced vs voiceless." },
      { contrast: "/ʒ/ vs /dʒ/", a: "vision", b: "pigeon", note: "Smooth buzz vs stop plus buzz." },
    ],
  },
  {
    symbol: "/h/",
    name: "h",
    group: "fricative",
    voiced: false,
    level: "beginner",
    difficulty: "easy",
    how: "Just breathe out gently before the vowel.",
    lips: "Ready for the next vowel.",
    teeth: "Apart.",
    tongue: "Neutral.",
    jaw: "Open.",
    mistakes: ["Making it too strong and throaty.", "Dropping it: 'hate' → 'ate'."],
    words: [
      { word: "hello", sentence: "She said hello to everyone." },
      { word: "have", sentence: "Do you have a moment to talk?" },
      { word: "behind", sentence: "The keys were behind the door." },
      { word: "who", sentence: "Who left this note here?" },
      { word: "perhaps", sentence: "Perhaps we should wait a little longer." },
      { word: "hospital", sentence: "He works at the local hospital." },
    ],
    sentences: ["He has a happy home.", "How high is the hill?"],
    pairs: [
      { contrast: "/h/ vs no /h/", a: "hair", b: "air", note: "Add a soft breath for /h/." },
      { contrast: "/h/ vs /k/", a: "hat", b: "cat", note: "Free breath vs hard stop." },
    ],
  },

  /* ------------------------------- affricates ------------------------------ */
  {
    symbol: "/tʃ/",
    name: "ch",
    group: "affricate",
    voiced: false,
    level: "beginner",
    difficulty: "medium",
    how: "Stop the air with the tongue, then release it into 'sh' — no voice.",
    lips: "Rounded and forward.",
    teeth: "Close.",
    tongue: "Front touches the ridge, then releases.",
    jaw: "Nearly closed.",
    mistakes: ["Using the Vietnamese 'ch', which is softer and has no release.", "Confusing it with /ʃ/."],
    words: [
      { word: "chair", sentence: "Please pull up a chair." },
      { word: "teacher", sentence: "Our teacher explained it clearly." },
      { word: "watch", sentence: "I like to watch the sunset." },
      { word: "much", sentence: "Thank you so much for coming." },
      { word: "kitchen", sentence: "She cooked dinner in the kitchen." },
      { word: "picture", sentence: "He took a picture of the view." },
    ],
    sentences: ["Which chair did the teacher choose?", "I watch much less each March."],
    pairs: [
      { contrast: "/tʃ/ vs /ʃ/", a: "chip", b: "ship", note: "Stop first vs smooth air." },
      { contrast: "/tʃ/ vs /dʒ/", a: "cheap", b: "jeep", note: "Voiceless vs voiced." },
    ],
  },
  {
    symbol: "/dʒ/",
    name: "j",
    group: "affricate",
    voiced: true,
    level: "beginner",
    difficulty: "medium",
    how: "Same as /tʃ/ but with the voice on.",
    lips: "Rounded and forward.",
    teeth: "Close.",
    tongue: "Front touches the ridge, then releases with a buzz.",
    jaw: "Nearly closed.",
    mistakes: ["Replacing it with /j/: 'job' → 'yob'.", "Replacing it with /z/."],
    words: [
      { word: "job", sentence: "He starts his new job tomorrow." },
      { word: "judge", sentence: "The judge listened carefully." },
      { word: "age", sentence: "She looks young for her age." },
      { word: "bridge", sentence: "We crossed the old bridge." },
      { word: "manager", sentence: "Please speak to the manager." },
      { word: "language", sentence: "Learning a new language takes time." },
    ],
    sentences: ["John's job is a joy.", "The manager just changed the language."],
    pairs: [
      { contrast: "/dʒ/ vs /tʃ/", a: "jeep", b: "cheap", note: "Voiced vs voiceless." },
      { contrast: "/dʒ/ vs /j/", a: "jet", b: "yet", note: "Stop plus buzz vs smooth glide." },
    ],
  },

  /* --------------------------------- nasals -------------------------------- */
  {
    symbol: "/m/",
    name: "m",
    group: "nasal",
    voiced: true,
    level: "beginner",
    difficulty: "easy",
    how: "Close the lips and hum through the nose.",
    lips: "Closed.",
    teeth: "Not involved.",
    tongue: "Neutral.",
    jaw: "Closed.",
    mistakes: ["Opening the lips too early at the end of a word.", "Cutting the hum short."],
    words: [
      { word: "man", sentence: "The man greeted us warmly." },
      { word: "some", sentence: "Can I borrow some sugar?" },
      { word: "summer", sentence: "We travel every summer." },
      { word: "time", sentence: "Take your time to decide." },
      { word: "remember", sentence: "I remember our first meeting." },
      { word: "problem", sentence: "There is no problem at all." },
    ],
    sentences: ["My mum makes me smile.", "Remember to come at midday."],
    pairs: [
      { contrast: "/m/ vs /n/", a: "some", b: "sun", note: "Lips closed vs tongue on the ridge." },
      { contrast: "/m/ vs /b/", a: "mat", b: "bat", note: "Air through the nose vs a lip release." },
    ],
  },
  {
    symbol: "/n/",
    name: "n",
    group: "nasal",
    voiced: true,
    level: "beginner",
    difficulty: "easy",
    how: "Tongue tip on the ridge, hum through the nose.",
    lips: "Relaxed.",
    teeth: "Apart.",
    tongue: "Tip on the ridge behind the upper teeth.",
    jaw: "Nearly closed.",
    mistakes: ["Turning final /n/ into /ŋ/.", "Dropping /n/ in 'and'."],
    words: [
      { word: "no", sentence: "There is no need to worry." },
      { word: "name", sentence: "Her name is written here." },
      { word: "nine", sentence: "The shop opens at nine." },
      { word: "again", sentence: "Please explain that again." },
      { word: "different", sentence: "This recipe tastes different." },
      { word: "know", sentence: "Do you know the way home?" },
    ],
    sentences: ["Nine new names.", "I know nothing at noon."],
    pairs: [
      { contrast: "/n/ vs /ŋ/", a: "sin", b: "sing", note: "Tongue tip up vs tongue back up." },
      { contrast: "/n/ vs /m/", a: "run", b: "rum", note: "Ridge vs lips." },
    ],
  },
  {
    symbol: "/ŋ/",
    name: "ng",
    group: "nasal",
    voiced: true,
    level: "intermediate",
    difficulty: "medium",
    how: "Back of the tongue up, hum through the nose — no /ɡ/ at the end.",
    lips: "Relaxed.",
    teeth: "Apart.",
    tongue: "Back against the soft palate; tip stays down.",
    jaw: "Half open.",
    mistakes: ["Adding a /ɡ/: 'singing' → 'singging'.", "Replacing it with /n/."],
    words: [
      { word: "sing", sentence: "She loves to sing in the choir." },
      { word: "long", sentence: "It was a long journey." },
      { word: "thinking", sentence: "I was thinking about you." },
      { word: "morning", sentence: "Good morning, everyone." },
      { word: "English", sentence: "He is studying English online." },
      { word: "young", sentence: "The team is quite young." },
    ],
    sentences: ["I am thinking of singing.", "Good morning, young English student."],
    pairs: [
      { contrast: "/ŋ/ vs /n/", a: "thing", b: "thin", note: "Tongue back vs tongue tip." },
      { contrast: "/ŋ/ vs /ŋɡ/", a: "singer", b: "finger", note: "'Singer' has no /ɡ/; 'finger' does." },
    ],
  },

  /* ------------------------------ approximants ----------------------------- */
  {
    symbol: "/l/",
    name: "l",
    group: "approximant",
    voiced: true,
    level: "beginner",
    difficulty: "medium",
    how: "Tongue tip presses the ridge; air flows around the sides.",
    lips: "Relaxed and open.",
    teeth: "Apart.",
    tongue: "Tip firmly on the ridge behind the upper teeth.",
    jaw: "Half open.",
    mistakes: [
      "Dropping the final /l/ in 'call' or 'people'.",
      "Turning /l/ into /n/ — a very common Vietnamese swap.",
    ],
    words: [
      { word: "light", sentence: "Please turn off the light." },
      { word: "like", sentence: "I really like this song." },
      { word: "little", sentence: "She has a little brother." },
      { word: "call", sentence: "I will call you tonight." },
      { word: "people", sentence: "Some people arrived late." },
      { word: "already", sentence: "We have already finished eating." },
    ],
    sentences: ["Little Lily likes it.", "Please call all the people."],
    pairs: [
      { contrast: "/l/ vs /r/", a: "light", b: "right", note: "Tongue touches vs tongue curls." },
      { contrast: "/l/ vs /n/", a: "low", b: "no", note: "Air out of the mouth vs out of the nose." },
    ],
  },
  {
    symbol: "/r/",
    name: "r",
    group: "approximant",
    voiced: true,
    level: "beginner",
    difficulty: "hard",
    how: "Curl the tongue up and back without touching anything, lips slightly round.",
    lips: "Slightly rounded, pushed forward.",
    teeth: "Apart.",
    tongue: "Tip curled up and back, never touching the roof.",
    jaw: "Half open.",
    mistakes: [
      "Rolling or tapping the /r/ like a Vietnamese 'r'.",
      "Replacing it with /z/ or /ʒ/.",
      "Adding /r/ where British English has none.",
    ],
    words: [
      { word: "red", sentence: "She wore a bright red dress." },
      { word: "very", sentence: "The soup was very tasty." },
      { word: "around", sentence: "We looked around the museum." },
      { word: "practise", sentence: "You should practise every day." },
      { word: "problem", sentence: "There is no problem at all." },
      { word: "already", sentence: "We have already finished eating." },
    ],
    sentences: ["Robert reads rarely.", "Try to practise the right words."],
    pairs: [
      { contrast: "/r/ vs /l/", a: "right", b: "light", note: "Curl vs touch." },
      { contrast: "/r/ vs /w/", a: "run", b: "won", note: "Tongue curl vs lips only." },
    ],
    accentNote: "American English pronounces /r/ everywhere; British RP drops it before a consonant or pause.",
  },
  {
    symbol: "/j/",
    name: "y glide",
    group: "approximant",
    voiced: true,
    level: "beginner",
    difficulty: "easy",
    how: "Start near /iː/ and glide straight into the next vowel.",
    lips: "Spread.",
    teeth: "Close.",
    tongue: "High and forward, then moving.",
    jaw: "Nearly closed, opening.",
    mistakes: ["Replacing it with /dʒ/: 'yes' → 'jes'.", "Making it a separate syllable."],
    words: [
      { word: "yes", sentence: "She said yes immediately." },
      { word: "year", sentence: "This year has passed quickly." },
      { word: "you", sentence: "I really appreciate you." },
      { word: "music", sentence: "They played soft music." },
      { word: "beautiful", sentence: "The garden looked beautiful." },
      { word: "usually", sentence: "I usually walk to work." },
    ],
    sentences: ["Yes, you are young.", "Beautiful music every year."],
    pairs: [
      { contrast: "/j/ vs /dʒ/", a: "yet", b: "jet", note: "Smooth glide vs stop plus buzz." },
      { contrast: "/juː/ vs /uː/", a: "cute", b: "coot", note: "With and without the glide." },
    ],
  },
  {
    symbol: "/w/",
    name: "w glide",
    group: "approximant",
    voiced: true,
    level: "beginner",
    difficulty: "medium",
    how: "Round the lips tightly, then glide into the vowel.",
    lips: "Tightly rounded, then opening.",
    teeth: "Not involved.",
    tongue: "Back and high, then moving.",
    jaw: "Nearly closed, opening.",
    mistakes: ["Using /v/ instead of /w/.", "Skipping the lip rounding in 'work' or 'want'."],
    words: [
      { word: "we", sentence: "We will meet again soon." },
      { word: "want", sentence: "What do you want to eat?" },
      { word: "work", sentence: "She walks to work every day." },
      { word: "away", sentence: "The dog ran away quickly." },
      { word: "question", sentence: "That's a very good question." },
      { word: "always", sentence: "He always arrives early." },
    ],
    sentences: ["We want to work with you.", "Why would we wait?"],
    pairs: [
      { contrast: "/w/ vs /v/", a: "wine", b: "vine", note: "Lips only vs teeth on lip." },
      { contrast: "/w/ vs /r/", a: "wed", b: "red", note: "Lips vs tongue curl." },
    ],
  },
];

export const SOUND_COUNT = PHONEMES.length;

/** The free allowance itself comes from billing_plans.limits
 * ("pronunciation_sounds_free_count") via entitlements.server.ts#getLimits —
 * the caller passes it in. */
export function isSoundIndexFree(index: number, freeCount: number): boolean {
  return index >= 0 && index < freeCount;
}

/** Canonical position in PHONEMES (or -1), matching either the RP or the
 * American symbol, so a caller can check the free allowance. */
export function findSoundIndex(symbol: string): number {
  const clean = `/${symbol.replaceAll("/", "").trim()}/`;
  return PHONEMES.findIndex((p) => p.symbol === clean || p.usSymbol === clean);
}

/** Every practice line /pronunciation actually offers for one sound — each
 * word, each sentence, and each minimal pair in the exact "a. b." form the
 * page sends. analysePronunciation only scores a target from this set, so a
 * free sound's id can't be paired with a locked sound's words. */
export function soundPracticeTargets(index: number): string[] {
  const sound = PHONEMES[index];
  if (!sound) return [];
  return [
    ...sound.words.map((w) => w.word),
    ...sound.words.map((w) => w.sentence),
    ...sound.sentences,
    ...sound.pairs.map((pair) => `${pair.a}. ${pair.b}.`),
  ];
}
