/**
 * Authoritative IPA lookup dictionary for pronunciation practice words
 * and Word Stress lesson items.
 */

export function getWordIpa(text: string): string | undefined {
  if (!text) return undefined;
  const raw = text.trim();
  const lower = raw.toLowerCase();

  // Exact phrase match first (for context-dependent words like "a record" vs "to record")
  if (WORD_IPA_MAP[lower]) return WORD_IPA_MAP[lower];

  // Without annotations like (noun), (verb), etc.
  const withoutParens = lower.replace(/\s*\([^)]*\)/g, "").trim();
  if (WORD_IPA_MAP[withoutParens]) return WORD_IPA_MAP[withoutParens];

  // Try without arrows: "afford → affordable" -> check parts
  if (lower.includes("→")) {
    const parts = lower.split("→").map((s) => s.trim());
    const ipas = parts.map((p) => getWordIpa(p)).filter(Boolean);
    if (ipas.length > 0) return ipas.join(" → ");
  }

  // Minimal pairs separated by period or slash: "ship. sheep." or "ship / sheep"
  if (/^[a-z'-]+\s*[./]\s*[a-z'-]+\.?$/i.test(lower)) {
    const parts = lower.split(/[./]/).map((s) => s.trim()).filter(Boolean);
    if (parts.length === 2) {
      const ipaA = WORD_IPA_MAP[parts[0]!];
      const ipaB = WORD_IPA_MAP[parts[1]!];
      if (ipaA && ipaB) return `${ipaA} · ${ipaB}`;
    }
  }

  // Clean common prefixes (articles, infinitives)
  const withoutPrefix = withoutParens.replace(/^(?:a|an|the|to)\s+/i, "").trim();
  if (WORD_IPA_MAP[withoutPrefix]) return WORD_IPA_MAP[withoutPrefix];

  // Single word lookup
  const words = withoutPrefix.split(/\s+/).filter(Boolean);
  if (words.length === 1 && WORD_IPA_MAP[words[0]!]) {
    return WORD_IPA_MAP[words[0]!];
  }

  return undefined;
}

export const WORD_IPA_MAP: Record<string, string> = {
  // ── 44 sounds example words ────────────────────────────────────────────────
  about: "əˈbaʊt",
  afraid: "əˈfreɪd",
  again: "əˈɡen",
  age: "eɪdʒ",
  air: "er",
  already: "ɔːlˈred.i",
  although: "ɔːlˈðoʊ",
  always: "ˈɔːl.weɪz",
  another: "əˈnʌð.ɚ",
  answer: "ˈæn.sɚ",
  answers: "ˈæn.sɚz",
  apple: "ˈæp.əl",
  around: "əˈraʊnd",
  avoid: "əˈvɔɪd",
  away: "əˈweɪ",
  baby: "ˈbeɪ.bi",
  bad: "bæd",
  bag: "bæɡ",
  banana: "bəˈnæn.ə",
  beautiful: "ˈbjuː.t̬ə.fəl",
  because: "bɪˈkəz",
  bed: "bed",
  before: "bɪˈfɔːr",
  behind: "bɪˈhaɪnd",
  believe: "bɪˈliːv",
  better: "ˈbet̬.ɚ",
  big: "bɪɡ",
  bird: "bɝːd",
  bit: "bɪt",
  blue: "bluː",
  boat: "boʊt",
  book: "bʊk",
  boy: "bɔɪ",
  bridge: "brɪdʒ",
  brother: "ˈbrʌð.ɚ",
  bus: "bʌs",
  busy: "ˈbɪz.i",
  call: "kɔːl",
  calm: "kɑːm",
  car: "kɑːr",
  care: "ker",
  career: "kəˈrɪr",
  cat: "kæt",
  caught: "kɔːt",
  chair: "tʃer",
  choice: "tʃɔɪs",
  choose: "tʃuːz",
  class: "klæs",
  clear: "klɪr",
  club: "klʌb",
  coffee: "ˈkɑː.fi",
  compare: "kəmˈper",
  could: "kʊd",
  cure: "kjʊr",
  cut: "kʌt",
  day: "deɪ",
  decide: "dɪˈsaɪd",
  decided: "dɪˈsaɪ.dɪd",
  decision: "dɪˈsɪʒ.ən",
  did: "dɪd",
  different: "ˈdɪf.ɚ.ənt",
  door: "dɔːr",
  down: "daʊn",
  eight: "eɪt",
  english: "ˈɪŋ.ɡlɪʃ",
  enjoy: "ɪnˈdʒɔɪ",
  enough: "ɪˈnʌf",
  far: "fɑːr",
  father: "ˈfɑː.ðɚ",
  first: "fɝːst",
  fish: "fɪʃ",
  five: "faɪv",
  food: "fuːd",
  forget: "fɚˈɡet",
  friend: "frend",
  full: "fʊl",
  fun: "fʌn",
  garage: "ɡəˈrɑːʒ",
  go: "ɡoʊ",
  good: "ɡʊd",
  green: "ɡriːn",
  hair: "her",
  happy: "ˈhæp.i",
  have: "hæv",
  head: "hed",
  healthy: "ˈhel.θi",
  heart: "hɑːrt",
  hello: "heˈloʊ",
  help: "help",
  here: "hɪr",
  hope: "hoʊp",
  hospital: "ˈhɑː.spɪ.t̬əl",
  hot: "hɑːt",
  house: "haʊs",
  idea: "aɪˈdiː.ə",
  important: "ɪmˈpɔːr.tnt",
  is: "ɪz",
  job: "dʒɑːb",
  judge: "dʒʌdʒ",
  kitchen: "ˈkɪtʃ.ən",
  know: "noʊ",
  language: "ˈlæŋ.ɡwɪdʒ",
  later: "ˈleɪ.t̬ɚ",
  law: "lɔː",
  learn: "lɝːn",
  leave: "liːv",
  life: "laɪf",
  light: "laɪt",
  like: "laɪk",
  little: "ˈlɪt̬.əl",
  live: "lɪv",
  long: "lɑːŋ",
  loud: "laʊd",
  love: "lʌv",
  machine: "məˈʃiːn",
  make: "meɪk",
  man: "mæn",
  manager: "ˈmæn.ə.dʒɚ",
  many: "ˈmen.i",
  market: "ˈmɑːr.kɪt",
  mature: "məˈtʃʊr",
  measure: "ˈmeʒ.ɚ",
  minute: "ˈmɪn.ɪt",
  money: "ˈmʌn.i",
  morning: "ˈmɔːr.nɪŋ",
  mother: "ˈmʌð.ɚ",
  mouth: "maʊθ",
  much: "mʌtʃ",
  music: "ˈmjuː.zɪk",
  my: "maɪ",
  name: "neɪm",
  nation: "ˈneɪ.ʃən",
  near: "nɪr",
  need: "niːd",
  night: "naɪt",
  nine: "naɪn",
  no: "noʊ",
  noise: "nɔɪz",
  not: "nɑːt",
  now: "naʊ",
  nurse: "nɝːs",
  office: "ˈɑː.fɪs",
  outside: "ˌaʊtˈsaɪd",
  over: "ˈoʊ.vɚ",
  pen: "pen",
  people: "ˈpiː.pəl",
  perhaps: "pɚˈhæps",
  person: "ˈpɝː.sən",
  phone: "foʊn",
  picture: "ˈpɪk.tʃɚ",
  pleasure: "ˈpleʒ.ɚ",
  point: "pɔɪnt",
  police: "pəˈliːs",
  poor: "pʊr",
  possible: "ˈpɑː.sə.bəl",
  practise: "ˈpræk.tɪs",
  prepare: "prɪˈper",
  problem: "ˈprɑː.bləm",
  pure: "pjʊr",
  put: "pʊt",
  question: "ˈkwes.tʃən",
  quick: "kwɪk",
  quiet: "ˈkwaɪ.ət",
  rain: "reɪn",
  really: "ˈriː.li",
  red: "red",
  remember: "rɪˈmem.bɚ",
  rich: "rɪtʃ",
  said: "sed",
  school: "skuːl",
  seat: "siːt",
  see: "siː",
  seven: "ˈsev.ən",
  she: "ʃiː",
  sheep: "ʃiːp",
  ship: "ʃɪp",
  shop: "ʃɑːp",
  sing: "sɪŋ",
  sit: "sɪt",
  some: "sʌm",
  something: "ˈsʌm.θɪŋ",
  start: "stɑːrt",
  stop: "stɑːp",
  summer: "ˈsʌm.ɚ",
  support: "səˈpɔːrt",
  sure: "ʃʊr",
  teacher: "ˈtiː.tʃɚ",
  ten: "ten",
  thank: "θæŋk",
  that: "ðæt",
  these: "ðiːz",
  think: "θɪŋk",
  thinking: "ˈθɪŋ.kɪŋ",
  this: "ðɪs",
  thought: "θɔːt",
  three: "θriː",
  time: "taɪm",
  together: "təˈɡeð.ɚ",
  tour: "tʊr",
  travel: "ˈtræv.əl",
  true: "truː",
  under: "ˈʌn.dɚ",
  usually: "ˈjuː.ʒu.ə.li",
  very: "ˈver.i",
  vision: "ˈvɪʒ.ən",
  voice: "vɔɪs",
  want: "wɑːnt",
  watch: "wɑːtʃ",
  water: "ˈwɔː.t̬ɚ",
  we: "wiː",
  weather: "ˈweð.ɚ",
  west: "west",
  wet: "wet",
  where: "wer",
  who: "huː",
  win: "wɪn",
  woman: "ˈwʊm.ən",
  work: "wɝːk",
  year: "jɪr",
  yes: "jes",
  you: "juː",
  young: "jʌŋ",
  zoo: "zuː",

  // ── Word Stress Lesson Items ──────────────────────────────────────────────
  hotel: "hoʊˈtel",
  computer: "kəmˈpjuː.t̬ɚ",
  "a record": "ˈrek.ɚd",
  "to record": "rɪˈkɔːrd",
  record: "ˈrek.ɚd",
  "a present": "ˈprez.ənt",
  "to present": "prɪˈzent",
  present: "ˈprez.ənt",
  "an increase": "ˈɪn.kriːs",
  "to increase": "ɪnˈkriːs",
  increase: "ˈɪn.kriːs",
  "a contract": "ˈkɑːn.trækt",
  "to contract": "kənˈtrækt",
  contract: "ˈkɑːn.trækt",
  "an object": "ˈɑːb.dʒɪkt",
  "to object": "əbˈdʒekt",
  object: "ˈɑːb.dʒɪkt",
  "an export": "ˈek.spɔːrt",
  "to export": "ɪkˈspɔːrt",
  export: "ˈek.spɔːrt",
  "a project": "ˈprɑː.dʒekt",
  "to project": "prəˈdʒekt",
  project: "ˈprɑː.dʒekt",
  "a progress": "ˈprɑː.ɡres",
  "to progress": "prəˈɡres",
  progress: "ˈprɑː.ɡres",
  "a suspect": "ˈsʌs.pekt",
  "to suspect": "səˈspekt",
  suspect: "ˈsʌs.pekt",
  "a permit": "ˈpɝː.mɪt",
  "to permit": "pɚˈmɪt",
  permit: "ˈpɝː.mɪt",
  "an address": "ˈæd.res",
  "to address": "əˈdres",
  address: "ˈæd.res",
  "a conflict": "ˈkɑːn.flɪkt",
  "to conflict": "kənˈflɪkt",
  conflict: "ˈkɑːn.flɪkt",
  "an estimate": "ˈes.tə.mət",
  "to estimate": "ˈes.tə.meɪt",
  estimate: "ˈes.tə.mət",
  "a graduate": "ˈɡrædʒ.u.ət",
  "to graduate": "ˈɡrædʒ.u.eɪt",
  graduate: "ˈɡrædʒ.u.ət",
  "a breakdown": "ˈbreɪk.daʊn",
  "to break down": "breɪk daʊn",
  "a setup": "ˈset.ʌp",
  "to set up": "set ʌp",
  "a check-in": "ˈtʃek.ɪn",
  "to check in": "tʃek ɪn",
  "desert (dry land)": "ˈdez.ɚt",
  "dessert (sweet food)": "dɪˈzɝːt",
  "content (satisfied)": "kənˈtent",
  "content (what's inside)": "ˈkɑːn.tent",
  photograph: "ˈfoʊ.t̬ə.ɡræf",
  photographer: "fəˈtɑː.ɡrə.fɚ",
  photographic: "ˌfoʊ.t̬əˈɡræf.ɪk",
  photography: "fəˈtɑː.ɡrə.fi",
  pronunciation: "prəˌnʌn.siˈeɪ.ʃən",
  international: "ˌɪn.t̬ɚˈnæʃ.nəl",
  economic: "ˌiː.kəˈnɑː.mɪk",
  economy: "ɪˈkɑː.nə.mi",
  national: "ˈnæʃ.nəl",
  ability: "əˈbɪl.ə.t̬i",
  accountant: "əˈkaʊn.tənt",
  affordable: "əˈfɔːr.də.bəl",
  airport: "ˈer.pɔːrt",
  algorithm: "ˈæl.ɡə.rɪ.ðəm",
  ambitious: "æmˈbɪʃ.əs",
  amsterdam: "ˈæm.stɚ.dæm",
  apology: "əˈpɑː.lə.dʒi",
  application: "ˌæp.ləˈkeɪ.ʃən",
  appointment: "əˈpɔɪnt.mənt",
  arrive: "əˈraɪv",
  assignment: "əˈsaɪn.mənt",
  athletic: "æθˈlet̬.ɪk",
  atm: "ˌeɪ.tiːˈem",
  attention: "əˈten.ʃən",
  ballet: "bælˈeɪ",
  bangkok: "ˈbæŋ.kɑːk",
  basketball: "ˈbæs.kɪt.bɑːl",
  begin: "bɪˈɡɪn",
  blackbird: "ˈblæk.bɝːd",
  budget: "ˈbʌdʒ.ɪt",
  buffet: "bəˈfeɪ",
  café: "kæfˈeɪ",
  celebration: "ˌsel.əˈbreɪ.ʃən",
  ceo: "ˌsiː.iːˈoʊ",
  characteristic: "ˌker.ək.təˈrɪs.tɪk",
  chicago: "ʃɪˈkɑː.ɡoʊ",
  chocolate: "ˈtʃɑːk.lət",
  cliché: "kliːˈʃeɪ",
  colleague: "ˈkɑː.liːɡ",
  comfortable: "ˈkʌm.fɚ.t̬ə.bəl",
  commercial: "kəˈmɝː.ʃəl",
  confident: "ˈkɑːn.fə.dənt",
  congratulations: "kənˌɡrætʃ.əˈleɪ.ʃənz",
  courageous: "kəˈreɪ.dʒəs",
  cultural: "ˈkʌl.tʃɚ.əl",
  curiosity: "ˌkjʊr.iˈɑː.sə.t̬i",
  curious: "ˈkjʊr.i.əs",
  currency: "ˈkɝː.ən.si",
  curriculum: "kəˈrɪk.jə.ləm",
  dangerous: "ˈdeɪn.dʒɚ.əs",
  database: "ˈdeɪ.t̬ə.beɪs",
  deadline: "ˈded.laɪn",
  delicious: "dɪˈlɪʃ.əs",
  difficult: "ˈdɪf.ə.kəlt",
  divorce: "dɪˈvɔːrs",
  download: "ˈdaʊn.loʊd",
  eleven: "ɪˈlev.ən",
  embarrassed: "ɪmˈber.əst",
  engineer: "ˌen.dʒɪˈnɪr",
  enormous: "əˈnɔːr.məs",
  essential: "ɪˈsen.ʃəl",
  every: "ˈev.ri",
  excited: "ɪkˈsaɪ.t̬ɪd",
  extraordinary: "ɪkˈstrɔːr.dən.er.i",
  forecast: "ˈfɔːr.kæst",
  forty: "ˈfɔːr.t̬i",
  fourteen: "ˌfɔːrˈtiːn",
  frustrated: "ˈfrʌs.treɪ.t̬ɪd",
  garden: "ˈɡɑːr.dən",
  gardening: "ˈɡɑːr.dən.ɪŋ",
  goodbye: "ɡʊdˈbaɪ",
  grandmother: "ˈɡræn.mʌð.ɚ",
  greenhouse: "ˈɡriːn.haʊs",
  historical: "hɪˈstɔːr.ɪ.kəl",
  humidity: "hjuːˈmɪd.ə.t̬i",
  hypothesis: "haɪˈpɑː.θə.sɪs",
  identification: "aɪˌden.t̬ə.fəˈkeɪ.ʃən",
  incredible: "ɪnˈkred.ə.bəl",
  individual: "ˌɪn.dəˈvɪdʒ.u.əl",
  information: "ˌɪn.fɚˈmeɪ.ʃən",
  ingredient: "ɪnˈɡriː.di.ənt",
  insurance: "ɪnˈʃʊr.əns",
  investment: "ɪnˈvest.mənt",
  italian: "ɪˈtæl.jən",
  italy: "ˈɪt̬.əl.i",
  itinerary: "aɪˈtɪn.ə.rer.i",
  japan: "dʒəˈpæn",
  japanese: "ˌdʒæp.ənˈiːz",
  journalist: "ˈdʒɝː.nə.lɪst",
  keyboard: "ˈkiː.bɔːrd",
  luggage: "ˈlʌɡ.ɪdʒ",
  marriage: "ˈmer.ɪdʒ",
  medicine: "ˈmed.ə.sən",
  memorize: "ˈmem.ə.raɪz",
  methodology: "ˌmeθ.əˈdɑː.lə.dʒi",
  monday: "ˈmʌn.deɪ",
  mortgage: "ˈmɔːr.ɡɪdʒ",
  natural: "ˈnætʃ.ɚ.əl",
  negotiate: "nəˈɡoʊ.ʃi.eɪt",
  nervous: "ˈnɝː.vəs",
  official: "əˈfɪʃ.əl",
  organization: "ˌɔːr.ɡən.əˈzeɪ.ʃən",
  organize: "ˈɔːr.ɡən.aɪz",
  original: "əˈrɪdʒ.ən.əl",
  parents: "ˈper.ənts",
  passport: "ˈpæs.pɔːrt",
  personal: "ˈpɝː.sən.əl",
  prescription: "prɪˈskrɪp.ʃən",
  realize: "ˈriː.ə.laɪz",
  reasonable: "ˈriː.zən.ə.bəl",
  recipe: "ˈres.ə.pi",
  relative: "ˈrel.ə.t̬ɪv",
  responsible: "rɪˈspɑːn.sə.bəl",
  responsibility: "rɪˌspɑːn.səˈbɪl.ə.t̬i",
  restaurant: "ˈres.tə.rɑːnt",
  scholarship: "ˈskɑː.lɚ.ʃɪp",
  scientific: "ˌsaɪ.ənˈtɪf.ɪk",
  september: "sepˈtem.bɚ",
  software: "ˈsɑːft.wer",
  specialize: "ˈspeʃ.ə.laɪz",
  spectacular: "spekˈtæk.jə.lɚ",
  suggest: "səˈdʒest",
  sunrise: "ˈsʌn.raɪz",
  swimming: "ˈswɪm.ɪŋ",
  symptom: "ˈsɪmp.təm",
  table: "ˈteɪ.bəl",
  television: "ˈtel.ə.vɪʒ.ən",
  temperature: "ˈtem.prə.tʃɚ",
  thirteen: "ˌθɝːˈtiːn",
  thirty: "ˈθɝː.t̬i",
  thunderstorm: "ˈθʌn.dɚ.stɔːrm",
  tomorrow: "təˈmɔːr.oʊ",
  toothbrush: "ˈtuːθ.brʌʃ",
  toronto: "təˈrɑːn.toʊ",
  umbrella: "ʌmˈbrel.ə",
  unbelievable: "ˌʌn.bɪˈliː.və.bəl",
  unhappy: "ʌnˈhæp.i",
  university: "ˌjuː.nəˈvɝː.sə.t̬i",
  usa: "ˌjuː.esˈeɪ",
  usual: "ˈjuː.ʒu.əl",
  variety: "vəˈraɪ.ə.t̬i",
  vegetable: "ˈvedʒ.tə.bəl",
  vietnam: "ˌvjetˈnɑːm",
  vietnamese: "ˌvjet.nəˈmiːz",
  volleyball: "ˈvɑː.li.bɑːl",
  weekend: "ˈwiːk.end",
  welcome: "ˈwel.kəm",
  window: "ˈwɪn.doʊ",
  wonderful: "ˈwʌn.dɚ.fəl",
  yesterday: "ˈjes.tɚ.deɪ",

  // Additional word stress compound phrases & items
  do: "duː",
  redo: "ˌriːˈduː",
  agree: "əˈɡriː",
  disagree: "ˌdɪs.əˈɡriː",
  sense: "sens",
  nonsense: "ˈnɑːn.sens",
  "black bird": "ˌblæk ˈbɝːd",
  "white house": "ˌwaɪt ˈhaʊs",
  "she's thirteen, not thirty.": "ʃiːz ˌθɝːˈtiːn, nɑːt ˈθɝː.t̬i",
  "a certificate": "sɚˈtɪf.ə.kət",
  "to certificate": "sɚˈtɪf.ə.keɪt",
  certificate: "sɚˈtɪf.ə.kət",
  id: "ˌaɪˈdiː",
  "well-known": "ˌwelˈnoʊn",
  "part-time": "ˌpɑːrtˈtaɪm",
  "self-employed": "ˌself.ɪmˈplɔɪd",
  "old-fashioned": "ˌoʊldˈfæʃ.ənd",
  "well-known author": "ˌwelˈnoʊn ˈɔː.θɚ",
  "two hundred dollars": "tuː ˈhʌn.drəd ˈdɑː.lɚz",
  "fifteen thousand": "ˌfɪfˈtiːn ˈθaʊ.zənd",
  "piece of cake": "ˌpiːs əv ˈkeɪk",
  "break a leg": "ˌbreɪk ə ˈleɡ",
  "once in a blue moon": "ˌwʌns ɪn ə ˌbluː ˈmuːn",
  "part-time job": "ˌpɑːrt.taɪm ˈdʒɑːb",
};
