import { createFileRoute, Link } from "@tanstack/react-router";

import { AppShell } from "@/components/lily/app-shell";
import { SectionHeading } from "@/components/lily/brand";
import { useI18n } from "@/lib/i18n";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — Lingora English" },
      {
        name: "description",
        content:
          "The terms that apply when you learn English with Lingora English, operated by Ms Thao English: accounts, subscriptions, fair use of AI practice and cancellation.",
      },
      { property: "og:title", content: "Terms of Service — Lingora English" },
      {
        property: "og:description",
        content: "Accounts, subscriptions, AI usage limits and cancellation terms for Lingora English.",
      },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary" },
    ],
  }),
  component: TermsPage,
});

const SECTIONS: { title: string; body: React.ReactNode }[] = [
  {
    title: "1. Who you are contracting with",
    body: "Lingora English (the \"Service\") is operated and sold by Ms Thao English (\"we\", \"us\", \"our\"). These Terms of Service form the agreement between you and Ms Thao English. You can reach us at support@msthaoenglish.com.",
  },
  {
    title: "2. Acceptance of these terms",
    body: "By creating an account, accessing or continuing to use the Service, you agree to be bound by these terms and by our Privacy Policy and Refund Policy. If you do not agree, do not use the Service. If you are using the Service on behalf of an organisation, you confirm you have authority to bind it; if you are an individual, you confirm you are of legal age in your country or are using the Service with a parent or guardian.",
  },
  {
    title: "3. Your account",
    body: "You need an account to practise with Lingora English. Keep your password confidential, give accurate details and keep them up to date, and use the platform only for learning English. You are responsible for all activity under your account. One account per learner.",
  },
  {
    title: "4. Free plan and usage limits",
    body: "The free plan includes a monthly allowance of AI practice (speaking, conversation and pronunciation) plus selected lessons. Allowances reset at the start of each calendar month and are enforced by our servers.",
  },
  {
    title: "5. Paid subscriptions and payment",
    body: (
      <>
        Premium and IELTS Pro are recurring subscriptions billed monthly or yearly and renew automatically until
        cancelled. Our order process is conducted by our online reseller Paddle.com. Paddle.com is the Merchant of
        Record for all our orders. Paddle provides all customer service inquiries and handles returns. Payment,
        billing, currency, tax and invoicing are governed by the{" "}
        <a
          href="https://www.paddle.com/legal/checkout-buyer-terms"
          target="_blank"
          rel="noopener noreferrer"
          className="text-primary underline"
        >
          Paddle Buyer Terms
        </a>
        . Trials, when offered, convert to a paid subscription unless cancelled before the trial ends.
      </>
    ),
  },
  {
    title: "6. Cancellation and refunds",
    body: (
      <>
        You can cancel at any time from My Subscription. Access continues until the end of the paid period, after
        which your account returns to the free plan. Your learning history is kept. Refunds are covered by our{" "}
        <Link to="/refunds" className="text-primary underline">
          Refund Policy
        </Link>{" "}
        — a 30-day money-back guarantee, with refunds processed by Paddle.
      </>
    ),
  },
  {
    title: "7. Intellectual property and licence",
    body: "The Service, including its software, lesson content, curriculum, audio, branding and the Lingora English character, is owned by Ms Thao English or its licensors and is protected by intellectual property laws. We grant you a limited, non-exclusive, non-transferable right to use the Service for your own learning within the plan you have selected. You may not copy, resell, redistribute, reverse engineer, scrape, or circumvent technical limits of the Service. You keep ownership of the recordings and text you submit, and grant us a limited licence to host and process them solely to provide the Service to you.",
  },
  {
    title: "8. AI feedback",
    body: "Scores, band estimates and corrections are generated by AI for practice purposes. Output may be inaccurate or incomplete. It is not an official exam result and is not a substitute for a certified examiner or professional advice.",
  },
  {
    title: "9. Acceptable use",
    body: "Do not use the Service unlawfully or fraudulently; do not attempt to bypass usage limits, probe or interfere with our security, upload malware, scrape the Service, or access another learner's data; and do not upload unlawful content, content that infringes someone else's rights, or recordings of people who have not agreed to be recorded.",
  },
  {
    title: "10. Service availability and warranties",
    body: "We work to keep the Service running but do not guarantee that it will be uninterrupted, error-free, or available at all times. To the fullest extent permitted by law, the Service is provided \"as is\" and we disclaim all implied warranties, including merchantability and fitness for a particular purpose.",
  },
  {
    title: "11. Suspension and termination",
    body: "We may suspend or terminate your access if you materially breach these terms, fail to pay, create a security or fraud risk, or repeatedly or seriously violate our acceptable use rules. Where reasonable we will warn you first. You may close your account at any time. On termination your right to use the Service ends; you may request an export of your learning data before deletion.",
  },
  {
    title: "12. Liability",
    body: "To the extent permitted by law, our aggregate liability to you is limited to the fees you paid in the 12 months before the claim, and we are not liable for indirect or consequential loss such as lost profits, data or goodwill. Nothing excludes liability for fraud, death or personal injury caused by negligence, or any liability that cannot be excluded by law.",
  },
  {
    title: "13. Changes",
    body: "We may update these terms as the platform evolves. Material changes will be announced in the app before they take effect, and continued use after that date means you accept the updated terms.",
  },
];

function TermsPage() {
  const { t, formatDate } = useI18n();
  return (
    <AppShell>
      <SectionHeading
        eyebrow={t("nav.terms")}
        title={t("legal.terms.title")}
        description={t("legal.updated", { date: formatDate(new Date("2026-09-02")) })}
      />
      <div className="lounge-panel mt-8 space-y-6 p-6 sm:p-8">
        {SECTIONS.map((section) => (
          <section key={section.title}>
            <h2 className="font-display text-lg text-foreground">{section.title}</h2>
            <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{section.body}</p>
          </section>
        ))}
      </div>
    </AppShell>
  );
}

