#!/usr/bin/env python3
"""
Adds the 51st lesson 'Practice' with 50 tailored drills to each of the 8 skill JSON files:
- word-stress.json
- sentence-stress.json
- intonation.json
- connected-speech.json
- reductions.json
- rhythm.json
- chunking.json
- fluency.json
"""
import json
import os

PRACTICE_LESSONS = {
    "word-stress": {
        "title": "Practice",
        "level": "intermediate",
        "difficulty": "medium",
        "accent": "us",
        "explain": "Master word stress across 50 essential English words. Listen to where the pitch peaks and the vowel elongates, then repeat with clear contrast between stressed and unstressed syllables.",
        "points": [
            "Make the stressed syllable louder, higher in pitch, and slightly longer.",
            "Reduce unstressed syllables to a neutral schwa /ə/ or short /ɪ/.",
            "Never pronounce every syllable with equal volume or length."
        ],
        "caution": "Do not rush through words; ensure the stressed syllable clearly dominates the word.",
        "items": [
            {"text": "banana", "pattern": "ba-NA-na", "note": "Second syllable is strong with a clear /æ/ sound."},
            {"text": "chocolate", "pattern": "CHOC-late", "note": "Two spoken syllables in natural speech, stress on the first."},
            {"text": "comfortable", "pattern": "COMF-ter-ble", "note": "Stress on the first syllable; four syllables condense to three."},
            {"text": "vegetable", "pattern": "VEG-ter-ble", "note": "First syllable carries the primary stress."},
            {"text": "interesting", "pattern": "IN-tres-ting", "note": "Stress on first syllable; middle 'e' is silent in natural speech."},
            {"text": "photograph", "pattern": "PHO-to-graph", "note": "First syllable stressed."},
            {"text": "photographer", "pattern": "pho-TO-gra-pher", "note": "Stress shifts to the second syllable."},
            {"text": "photographic", "pattern": "pho-to-GRAPH-ic", "note": "Stress shifts to the third syllable before -ic."},
            {"text": "decision", "pattern": "de-CI-sion", "note": "Stress on the syllable immediately preceding -sion."},
            {"text": "information", "pattern": "in-for-MA-tion", "note": "Primary stress falls on the syllable before -tion."},
            {"text": "education", "pattern": "ed-u-CA-tion", "note": "Stress on the third syllable 'CA'."},
            {"text": "economy", "pattern": "e-CON-o-my", "note": "Stress on second syllable 'CON'."},
            {"text": "economic", "pattern": "e-co-NOM-ic", "note": "Stress shifts to third syllable 'NOM' before -ic."},
            {"text": "university", "pattern": "u-ni-VER-si-ty", "note": "Stress falls on 'VER' before the -ity suffix."},
            {"text": "possibility", "pattern": "pos-si-BIL-i-ty", "note": "Stress on 'BIL' before -ity."},
            {"text": "technology", "pattern": "tech-NOL-o-gy", "note": "Second syllable 'NOL' takes the primary stress."},
            {"text": "technological", "pattern": "tech-no-LOG-i-cal", "note": "Stress shifts to 'LOG' before -ical."},
            {"text": "democracy", "pattern": "de-MOC-ra-cy", "note": "Second syllable 'MOC' is stressed."},
            {"text": "democratic", "pattern": "dem-o-CRAT-ic", "note": "Stress shifts to 'CRAT' before -ic."},
            {"text": "communicate", "pattern": "com-MU-ni-cate", "note": "Second syllable 'MU' carries the main beat."},
            {"text": "communication", "pattern": "com-mu-ni-CA-tion", "note": "Stress shifts to 'CA' before -tion."},
            {"text": "participate", "pattern": "par-TIC-i-pate", "note": "Second syllable 'TIC' is emphasized."},
            {"text": "opportunity", "pattern": "op-por-TU-ni-ty", "note": "Primary stress on 'TU'."},
            {"text": "development", "pattern": "de-VEL-op-ment", "note": "Second syllable 'VEL' is stressed."},
            {"text": "environment", "pattern": "en-VI-ron-ment", "note": "Second syllable 'VI' takes the stress."},
            {"text": "relationship", "pattern": "re-LA-tion-ship", "note": "Second syllable 'LA' is stressed."},
            {"text": "conversation", "pattern": "con-ver-SA-tion", "note": "Third syllable 'SA' carries primary stress."},
            {"text": "organization", "pattern": "or-gan-i-ZA-tion", "note": "Primary stress on 'ZA' before -tion."},
            {"text": "pronunciation", "pattern": "pro-nun-ci-A-tion", "note": "Stress on 'A' before -tion; note 'nun' not 'noun'."},
            {"text": "recommend", "pattern": "rec-om-MEND", "note": "Third syllable 'MEND' receives primary stress."},
            {"text": "understand", "pattern": "un-der-STAND", "note": "Final syllable 'STAND' carries main stress."},
            {"text": "guarantee", "pattern": "guar-an-TEE", "note": "Final syllable 'TEE' is stressed."},
            {"text": "volunteer", "pattern": "vol-un-TEER", "note": "Final syllable 'TEER' receives the primary stress."},
            {"text": "employee", "pattern": "em-ploy-EE", "note": "Final syllable 'EE' is stressed."},
            {"text": "afternoon", "pattern": "af-ter-NOON", "note": "Main stress on 'NOON'."},
            {"text": "seventeen", "pattern": "sev-en-TEEN", "note": "Stress on 'TEEN' in isolation or contrast."},
            {"text": "seventy", "pattern": "SEV-en-ty", "note": "Stress on 'SEV'; clearly distinct from seventeen."},
            {"text": "passport", "pattern": "PASS-port", "note": "Compound noun: primary stress on first word."},
            {"text": "airline", "pattern": "AIR-line", "note": "Compound noun: stress the first word 'AIR'."},
            {"text": "toothpaste", "pattern": "TOOTH-paste", "note": "Compound noun: stress the first element."},
            {"text": "sunglasses", "pattern": "SUN-glass-es", "note": "Compound noun: strong first syllable 'SUN'."},
            {"text": "whiteboard", "pattern": "WHITE-board", "note": "Compound noun: 'WHITE' is stressed, unlike phrase 'white BOARD'."},
            {"text": "supermarket", "pattern": "SU-per-mar-ket", "note": "Strong initial stress on 'SU'."},
            {"text": "photocopy", "pattern": "PHO-to-cop-y", "note": "Primary stress on the first syllable."},
            {"text": "a PRO-ject", "pattern": "PRO-ject (noun)", "note": "Noun: stress on the first syllable."},
            {"text": "to pro-JECT", "pattern": "pro-JECT (verb)", "note": "Verb: stress shifts to the second syllable."},
            {"text": "an OB-ject", "pattern": "OB-ject (noun)", "note": "Noun: first syllable stressed."},
            {"text": "to ob-JECT", "pattern": "ob-JECT (verb)", "note": "Verb: second syllable stressed."},
            {"text": "a PER-mit", "pattern": "PER-mit (noun)", "note": "Noun: stress on 'PER'."},
            {"text": "to per-MIT", "pattern": "per-MIT (verb)", "note": "Verb: stress on 'MIT'."}
        ]
    },
    "sentence-stress": {
        "title": "Practice",
        "level": "intermediate",
        "difficulty": "medium",
        "accent": "us",
        "explain": "Train natural sentence stress across 50 everyday phrases. Focus on emphasizing content words (nouns, main verbs, adjectives) while reducing grammar and helper words.",
        "points": [
            "Content words (key information) are pronounced louder, clearer, and longer.",
            "Function words (pronouns, prepositions, auxiliaries) are compressed and spoken rapidly.",
            "Shifting the stress to a different word changes the focus or implied meaning."
        ],
        "caution": "Avoid equal emphasis on every word; English rhythm requires distinct peaks and valleys.",
        "items": [
            {"text": "I lost my phone yesterday.", "pattern": "I LOST my PHONE YES-ter-day.", "note": "Main emphasis on 'lost', 'phone', and 'yesterday'."},
            {"text": "She bought a beautiful new car.", "pattern": "she BOUGHT a BEAU-ti-ful NEW CAR.", "note": "'bought', 'beautiful', 'new', 'car' carry the sentence beats."},
            {"text": "Can you pick me up at the airport?", "pattern": "can you PICK me UP at the AIR-port?", "note": "Stress on phrasal verb 'pick up' and 'airport'."},
            {"text": "We need to discuss the project schedule.", "pattern": "we NEED to dis-CUSS the PRO-ject SCHED-ule.", "note": "Grammar words 'we', 'to', 'the' are quick and soft."},
            {"text": "He didn't know the answer to the question.", "pattern": "he DID-n't KNOW the AN-swer to the QUES-tion.", "note": "'didn't' and 'know' take focus."},
            {"text": "I was waiting for you in the lobby.", "pattern": "I was WAIT-ing for you in the LOB-by.", "note": "'waiting' and 'lobby' carry the content."},
            {"text": "What are you planning to do tonight?", "pattern": "WHAT are you PLAN-ning to DO to-NIGHT?", "note": "Question word 'what', 'planning', 'do', 'tonight' are stressed."},
            {"text": "Where did you leave your apartment keys?", "pattern": "WHERE did you LEAVE your a-PART-ment KEYS?", "note": "'where', 'leave', 'apartment', 'keys' take the primary beats."},
            {"text": "Why didn't you call me earlier?", "pattern": "WHY DID-n't you CALL me EAR-li-er?", "note": "Negation 'didn't' and 'call' are emphasized."},
            {"text": "How long will the presentation take?", "pattern": "HOW LONG will the pres-en-TA-tion TAKE?", "note": "'how long', 'presentation', and 'take' are stressed."},
            {"text": "I didn't steal the money.", "pattern": "I didn't STEAL the MON-ey.", "note": "Neutral statement focusing on the action and object."},
            {"text": "I didn't steal the money.", "pattern": "I didn't steal the MON-ey.", "note": "Focus on 'money' implies I stole something else."},
            {"text": "I didn't steal the money.", "pattern": "I didn't STEAL the money.", "note": "Focus on 'steal' implies I borrowed it."},
            {"text": "I didn't steal the money.", "pattern": "I DID-N'T steal the money.", "note": "Emphatic denial of the entire action."},
            {"text": "I didn't steal the money.", "pattern": "I didn't steal the money.", "note": "Emphasis on 'I' implies someone else did it."},
            {"text": "She wants green tea, not black tea.", "pattern": "she wants GREEN tea, not BLACK tea.", "note": "Contrastive stress on the adjectives 'green' and 'black'."},
            {"text": "We're meeting on Tuesday, not Thursday.", "pattern": "we're meeting on TUES-day, not THURS-day.", "note": "Contrasting the specific days."},
            {"text": "I asked for a hot latte, not an iced one.", "pattern": "I asked for a HOT latte, not an ICED one.", "note": "Stress on 'hot' vs 'iced'."},
            {"text": "The flight was delayed by three hours.", "pattern": "the flight was de-LAYED by THREE HOURS.", "note": "'delayed' and 'three hours' receive key emphasis."},
            {"text": "Could you please send me the report?", "pattern": "could you please SEND me the re-PORT?", "note": "Polite request stressing the action 'send' and object 'report'."},
            {"text": "I'd really appreciate your help with this.", "pattern": "I'd REAL-ly ap-PRE-ci-ate your HELP with this.", "note": "'really', 'appreciate', and 'help' are stressed."},
            {"text": "There's no way we can finish this today.", "pattern": "there's NO WAY we can FIN-ish this to-DAY.", "note": "Strong emphasis on 'no way' and 'finish'."},
            {"text": "Are you absolutely sure about that?", "pattern": "are you AB-so-lute-ly SURE a-bout that?", "note": "Adverb 'absolutely' and adjective 'sure' are prominent."},
            {"text": "I have never seen anything like this before.", "pattern": "I have NEV-er SEEN AN-y-thing like THIS be-fore.", "note": "Negative adverb 'never' and 'seen' take stress."},
            {"text": "The coffee shop is right around the corner.", "pattern": "the COF-fee shop is RIGHT a-ROUND the COR-ner.", "note": "Directional 'right around the corner' takes emphasis."},
            {"text": "Let's grab a quick bite before the movie.", "pattern": "let's grab a QUICK BITE be-fore the MO-vie.", "note": "'quick bite' and 'movie' receive beats."},
            {"text": "Don't forget to lock the front door.", "pattern": "DON'T for-GET to LOCK the FRONT DOOR.", "note": "'don't', 'forget', 'lock', 'front door' carry stress."},
            {"text": "She always arrives ten minutes early.", "pattern": "she AL-ways ar-RIVES TEN MIN-utes EAR-ly.", "note": "Frequency adverb 'always' and time 'ten minutes early' stand out."},
            {"text": "We need to make a decision right now.", "pattern": "we need to make a de-CI-sion RIGHT NOW.", "note": "Urgency stressed on 'decision' and 'right now'."},
            {"text": "Can I have a glass of water, please?", "pattern": "can I have a GLASS of WA-ter, PLEASE?", "note": "'glass', 'water', and 'please' are highlighted."},
            {"text": "I completely forgot about our meeting.", "pattern": "I com-PLETE-ly for-GOT a-bout our MEET-ing.", "note": "Intensifier 'completely' and verb 'forgot' are strong."},
            {"text": "That was the best meal I've ever had.", "pattern": "that was the BEST MEAL I've EV-er HAD.", "note": "Superlative 'best meal' and 'ever had' carry peak pitch."},
            {"text": "It takes about thirty minutes to get there.", "pattern": "it takes about THIR-ty MIN-utes to GET THERE.", "note": "Number 'thirty minutes' and destination 'get there' are stressed."},
            {"text": "Would you mind closing the window?", "pattern": "would you MIND CLOS-ing the WIN-dow?", "note": "'mind', 'closing', and 'window' take the beats."},
            {"text": "I can't believe how fast time flies.", "pattern": "I CAN'T be-LIEVE how FAST TIME FLIES.", "note": "Negative 'can't believe' and idiom 'fast time flies' are stressed."},
            {"text": "The weather forecast said it would rain.", "pattern": "the WEATH-er FORE-cast said it would RAIN.", "note": "'weather forecast' and 'rain' are the content words."},
            {"text": "He decided to study abroad next year.", "pattern": "he de-CI-ded to STUD-y a-BROAD NEXT YEAR.", "note": "'decided', 'study abroad', and 'next year' carry meaning."},
            {"text": "She graduated with honors from college.", "pattern": "she GRAD-u-a-ted with HON-ors from COL-lege.", "note": "'graduated', 'honors', and 'college' take stress."},
            {"text": "My train was canceled due to signal failure.", "pattern": "my TRAIN was CAN-celed due to SIG-nal FAIL-ure.", "note": "Content words 'train', 'canceled', 'signal failure' stand out."},
            {"text": "I'll let you know as soon as I hear anything.", "pattern": "I'll LET you KNOW as SOON as I HEAR AN-y-thing.", "note": "'let know', 'soon', 'hear anything' receive rhythm beats."},
            {"text": "Are we still on for lunch tomorrow?", "pattern": "are we STILL ON for LUNCH to-MOR-row?", "note": "'still on', 'lunch', and 'tomorrow' are prominent."},
            {"text": "You did a fantastic job on this presentation.", "pattern": "you did a fan-TAS-tic JOB on this pres-en-TA-tion.", "note": "Compliment stresses 'fantastic job' and 'presentation'."},
            {"text": "I don't think that's a very good idea.", "pattern": "I DON'T THINK that's a very GOOD i-DEA.", "note": "'don't think' and 'good idea' carry focus."},
            {"text": "The internet connection is really slow today.", "pattern": "the IN-ter-net con-NEC-tion is REAL-ly SLOW to-DAY.", "note": "'internet connection', 'really slow', 'today' are stressed."},
            {"text": "Could you repeat that more slowly, please?", "pattern": "could you re-PEAT that more SLOW-ly, PLEASE?", "note": "Key requests: 'repeat', 'slowly', 'please'."},
            {"text": "I'm looking forward to seeing you this weekend.", "pattern": "I'm look-ing FOR-ward to SEE-ing you this WEEK-end.", "note": "Phrasal idiom 'looking forward', 'seeing', 'weekend'."},
            {"text": "Make sure you double-check your work.", "pattern": "make SURE you DOU-ble-CHECK your WORK.", "note": "Imperative 'sure', 'double-check', 'work'."},
            {"text": "Nobody told me about the schedule change.", "pattern": "NO-bod-y TOLD me a-bout the SCHED-ule CHANGE.", "note": "'nobody told' and 'schedule change' are emphasized."},
            {"text": "It's not what you say, it's how you say it.", "pattern": "it's not WHAT you SAY, it's HOW you SAY it.", "note": "Contrasting 'what' with 'how'."},
            {"text": "Practice makes perfect when learning a language.", "pattern": "PRAC-tice makes PER-fect when LEARN-ing a LAN-guage.", "note": "Proverb: 'practice', 'perfect', 'learning', 'language' carry the beat."}
        ]
    },
    "intonation": {
        "title": "Practice",
        "level": "intermediate",
        "difficulty": "medium",
        "accent": "us",
        "explain": "Master English pitch contour and melody across 50 sentences: falling intonation for definitive statements and Wh-questions, rising intonation for Yes/No questions, and fall-rise for politeness.",
        "points": [
            "Falling tone (↘): signals completion, certainty, and commands.",
            "Rising tone (↗): signals questions requiring Yes/No or checking uncertainty.",
            "Fall-rise tone (↘↗): signals reservations, polite corrections, or unfinished thoughts."
        ],
        "caution": "Avoid 'uptalk' (ending statements with a rise); it makes you sound unsure of your own statements.",
        "items": [
            {"text": "My name is David. ↘", "pattern": "my name is DA-vid ↘", "note": "Definitive statement: clear falling tone at the end."},
            {"text": "I live in Chicago. ↘", "pattern": "I live in chi-CA-go ↘", "note": "Final statement: pitch steps down on the last syllable."},
            {"text": "The store closes at nine. ↘", "pattern": "the store closes at NINE ↘", "note": "Factual statement ends with a decisive drop in pitch."},
            {"text": "We arrived on time. ↘", "pattern": "we arrived on TIME ↘", "note": "Firm finality: pitch drops smoothly to the lowest level."},
            {"text": "I've finished my homework. ↘", "pattern": "I've finished my HOME-work ↘", "note": "Statement of completion falls at the end."},
            {"text": "Where is the nearest subway station? ↘", "pattern": "where is the nearest SUB-way sta-tion? ↘", "note": "Wh-question: starts high and finishes with a falling tone."},
            {"text": "What time does the train leave? ↘", "pattern": "what time does the TRAIN leave? ↘", "note": "Wh-question falls at the end like a statement."},
            {"text": "Who is responsible for this project? ↘", "pattern": "who is responsible for this PRO-ject? ↘", "note": "Wh-question: downward glide on the final content word."},
            {"text": "Why are you leaving so early? ↘", "pattern": "why are you leaving so EAR-ly? ↘", "note": "Wh-question: pitch drops firmly on 'early'."},
            {"text": "How did you solve this problem? ↘", "pattern": "how did you solve this PROB-lem? ↘", "note": "Wh-question ends with downward pitch."},
            {"text": "Do you speak English? ↗", "pattern": "do you speak ENG-lish? ↗", "note": "Yes/No question: voice glides up significantly at the end."},
            {"text": "Are you ready to order? ↗", "pattern": "are you ready to OR-der? ↗", "note": "Yes/No question rises on the final syllable."},
            {"text": "Have you seen my glasses anywhere? ↗", "pattern": "have you seen my glasses AN-y-where? ↗", "note": "Yes/No inquiry glides upward on the last word."},
            {"text": "Can you hear me clearly? ↗", "pattern": "can you hear me CLEAR-ly? ↗", "note": "Yes/No question: rising tone confirms audibility."},
            {"text": "Is this seat taken? ↗", "pattern": "is this seat TAK-en? ↗", "note": "Yes/No question rises politely at the end."},
            {"text": "Would you like some coffee? ↗", "pattern": "would you like some COF-fee? ↗", "note": "Offer rises gently to invite a response."},
            {"text": "Did you receive my email? ↗", "pattern": "did you receive my E-mail? ↗", "note": "Verification question rises on 'email'."},
            {"text": "Will it rain tomorrow? ↗", "pattern": "will it rain to-MOR-row? ↗", "note": "Yes/No question with rising intonation."},
            {"text": "I bought apples ↗, oranges ↗, and bananas. ↘", "pattern": "AP-ples ↗, OR-ang-es ↗, and ba-NA-nas ↘", "note": "List: rise on non-final items, fall on the final item."},
            {"text": "We visited Rome ↗, Paris ↗, and London. ↘", "pattern": "ROME ↗, PAR-is ↗, and LON-don ↘", "note": "Listing intonation: rising melody until the closing fall."},
            {"text": "You can have tea ↗, or coffee. ↘", "pattern": "you can have TEA ↗, or COF-fee ↘", "note": "Alternative question: rise on first choice, fall on the second."},
            {"text": "Would you prefer morning ↗, or afternoon? ↘", "pattern": "pre-fer MORN-ing ↗, or af-ter-NOON? ↘", "note": "Choice question: rise then fall."},
            {"text": "It's cold outside, isn't it? ↘", "pattern": "it's cold out-side, IS-n't it? ↘", "note": "Tag question seeking agreement: falling tone."},
            {"text": "You're coming tonight, aren't you? ↗", "pattern": "you're coming to-night, AREN'T you? ↗", "note": "Tag question seeking genuine confirmation: rising tone."},
            {"text": "He didn't call, did he? ↘", "pattern": "he didn't call, DID he? ↘", "note": "Expecting confirmation: falling tone."},
            {"text": "You haven't seen her, have you? ↗", "pattern": "you haven't seen her, HAVE you? ↗", "note": "Genuine uncertainty: rising pitch on tag."},
            {"text": "Excuse me? ↗", "pattern": "ex-CUSE me? ↗", "note": "Asking someone to repeat: sharp rise."},
            {"text": "Excuse me. ↘", "pattern": "ex-CUSE me. ↘", "note": "Polite apology or getting attention: gentle fall."},
            {"text": "Really? ↗", "pattern": "REAL-ly? ↗", "note": "Expressing surprise or doubt: rising pitch."},
            {"text": "Really. ↘", "pattern": "REAL-ly. ↘", "note": "Confirming fact: falling pitch."},
            {"text": "Well, I suppose so... ↘↗", "pattern": "well, I sup-pose SO... ↘↗", "note": "Hesitation or reservation: fall-rise intonation."},
            {"text": "The food was good ↘↗, but expensive. ↘", "pattern": "the food was GOOD ↘↗, but ex-PEN-sive ↘", "note": "Fall-rise on first clause signals an upcoming contrast."},
            {"text": "Although it was raining ↗, we went for a walk. ↘", "pattern": "al-though it was RAIN-ing ↗, we went for a WALK ↘", "note": "Dependent clause rises, independent clause falls."},
            {"text": "If you need anything ↗, just let me know. ↘", "pattern": "if you need AN-y-thing ↗, just let me KNOW ↘", "note": "Conditional clause rises slightly, main clause concludes down."},
            {"text": "When you arrive ↗, give me a call. ↘", "pattern": "when you ar-RIVE ↗, give me a CALL ↘", "note": "Time clause rises, imperative falls."},
            {"text": "Please sit down. ↘", "pattern": "please sit DOWN ↘", "note": "Firm, polite instruction: falling contour."},
            {"text": "Turn off the lights before you leave. ↘", "pattern": "turn off the LIGHTS before you LEAVE ↘", "note": "Direct instruction falls at the end."},
            {"text": "Help! ↘", "pattern": "HELP! ↘", "note": "Exclamation: high pitch dropping sharply with force."},
            {"text": "What a wonderful surprise! ↘", "pattern": "what a won-der-ful sur-PRISE! ↘", "note": "Exclamatory statement falls decisively."},
            {"text": "Good morning! ↘", "pattern": "good MORN-ing! ↘", "note": "Warm, cheerful greeting falls naturally."},
            {"text": "Good night. ↘", "pattern": "good NIGHT. ↘", "note": "Gentle falling tone signals farewell."},
            {"text": "See you later! ↘", "pattern": "see you LA-ter! ↘", "note": "Friendly departure falls at the end."},
            {"text": "Thank you very much. ↘", "pattern": "thank you VER-y much ↘", "note": "Sincere gratitude ends on a downward pitch."},
            {"text": "You're welcome. ↘", "pattern": "you're WEL-come ↘", "note": "Relaxed falling tone."},
            {"text": "Are you sure? ↗", "pattern": "are you SURE? ↗", "note": "Questioning certainty: upward glide."},
            {"text": "I'm certain. ↘", "pattern": "I'm CER-tain ↘", "note": "Certainty: sharp falling tone."},
            {"text": "I don't know... ↘↗", "pattern": "I don't KNOW... ↘↗", "note": "Uncertainty or reluctance: fall-rise intonation."},
            {"text": "Can I help you? ↗", "pattern": "can I HELP you? ↗", "note": "Helpful customer service offer rises gently."},
            {"text": "How can I help you? ↘", "pattern": "how can I HELP you? ↘", "note": "Wh-question: falls at the end."},
            {"text": "That's fantastic news! ↘", "pattern": "that's fan-TAS-tic NEWS! ↘", "note": "Enthusiastic statement: high peak followed by full drop."}
        ]
    },
    "connected-speech": {
        "title": "Practice",
        "level": "intermediate",
        "difficulty": "medium",
        "accent": "us",
        "explain": "Master natural connected speech across 50 examples: linking consonant to vowel (cat in a bag), intrusive /w/ and /j/, linking /r/, and blending across word boundaries.",
        "points": [
            "Consonant to vowel: link the final consonant directly into the starting vowel of the next word.",
            "Vowel to vowel: smoothly bridge with an unwritten /w/ or /j/ sound.",
            "Assimilation & blending: sounds adapt to their neighbors for maximum vocal ease."
        ],
        "caution": "Do not insert artificial pauses between words; let your voice stream continuously.",
        "items": [
            {"text": "hold on", "pattern": "hol-don", "note": "Consonant to vowel link: the 'd' carries into 'on'."},
            {"text": "pick it up", "pattern": "pi-ki-tup", "note": "Two consecutive links: 'k' to 'it', 't' to 'up'."},
            {"text": "not at all", "pattern": "no-ta-tall", "note": "Both 't' sounds link smoothly forward."},
            {"text": "check it out", "pattern": "che-ki-tout", "note": "'k' links to 'it', 't' flaps and links to 'out'."},
            {"text": "turn off", "pattern": "tur-noff", "note": "Final 'n' attaches to 'off'."},
            {"text": "come in", "pattern": "com-min", "note": "Final 'm' sound flows directly into 'in'."},
            {"text": "an apple", "pattern": "a-napple", "note": "'n' bridges the two words into a single unit."},
            {"text": "this afternoon", "pattern": "thi-safternoon", "note": "The 's' sound leaps onto 'afternoon'."},
            {"text": "take a break", "pattern": "tay-ka-break", "note": "'k' links smoothly onto 'a'."},
            {"text": "leave it alone", "pattern": "lee-vi-talone", "note": "'v' to 'it', then 't' to 'alone'."},
            {"text": "read a book", "pattern": "ree-da-book", "note": "'d' sound glides directly into 'a'."},
            {"text": "stand up", "pattern": "stan-dup", "note": "The final 'd' attaches to 'up'."},
            {"text": "wake up", "pattern": "way-kup", "note": "The 'k' sound carries into 'up'."},
            {"text": "look at that", "pattern": "loo-kat that", "note": "Linking 'k' to 'at'."},
            {"text": "stop it", "pattern": "stah-pit", "note": "The 'p' sound links seamlessly onto 'it'."},
            {"text": "go out", "pattern": "go-(w)-out", "note": "Intrusive /w/ bridges the two round vowels."},
            {"text": "do it", "pattern": "do-(w)-it", "note": "Insert a smooth /w/ glide between 'do' and 'it'."},
            {"text": "show us", "pattern": "show-(w)-us", "note": "Gentle /w/ glide between 'ow' and 'us'."},
            {"text": "too easy", "pattern": "too-(w)-easy", "note": "Lips glide with a brief /w/ into 'easy'."},
            {"text": "so I said", "pattern": "so-(w)-I said", "note": "Bridge 'so' and 'I' with a soft /w/."},
            {"text": "see it", "pattern": "see-(j)-it", "note": "Intrusive /j/ (y sound) bridges the front vowels."},
            {"text": "I agree", "pattern": "I-(j)-agree", "note": "Insert a smooth /j/ glide between 'I' and 'agree'."},
            {"text": "be honest", "pattern": "be-(j)-honest", "note": "Front vowel /iː/ glides with /j/ into 'honest'."},
            {"text": "say it again", "pattern": "say-(j)-it again", "note": "High front glide /j/ attaches to 'it'."},
            {"text": "stay away", "pattern": "stay-(j)-away", "note": "Seamless /j/ transition from 'stay' to 'away'."},
            {"text": "the only one", "pattern": "the-(j)-only one", "note": "'the' pronounced as /ði/ links with a /j/ glide into 'only'."},
            {"text": "four apples", "pattern": "four-(r)-apples", "note": "Linking 'r' connects directly into 'apples'."},
            {"text": "far away", "pattern": "far-(r)-away", "note": "The 'r' sound carries into 'away'."},
            {"text": "more and more", "pattern": "more-(r)-and more", "note": "The 'r' links into 'and'."},
            {"text": "never again", "pattern": "never-(r)-again", "note": "Smooth 'r' connection into 'again'."},
            {"text": "water is cold", "pattern": "water-(r)-is cold", "note": "The final 'r' connects into 'is'."},
            {"text": "what do you think?", "pattern": "whaddya think?", "note": "Assimilation: 'what do you' contracts smoothly."},
            {"text": "don't you know?", "pattern": "don-chu know?", "note": "'t' + 'y' blend into a /tʃ/ (ch) sound."},
            {"text": "did you see it?", "pattern": "did-joo see it?", "note": "'d' + 'y' blend into a /dʒ/ (j) sound."},
            {"text": "could you help me?", "pattern": "cood-joo help me?", "note": "'could you' blends into 'cood-joo'."},
            {"text": "would you mind?", "pattern": "wood-joo mind?", "note": "'would you' assimilates into 'wood-joo'."},
            {"text": "nice to meet you", "pattern": "meet-chu", "note": "'t' at end of 'meet' + 'you' becomes 'meet-chu'."},
            {"text": "got you!", "pattern": "got-cha!", "note": "'got you' assimilates to 'gotcha'."},
            {"text": "I bet you will.", "pattern": "I bet-chu will.", "note": "'bet you' blends into 'bet-chu'."},
            {"text": "as you know", "pattern": "az-zhoo know", "note": "'s' + 'y' blend into a /ʒ/ sound."},
            {"text": "bless you!", "pattern": "blesh-yoo!", "note": "'s' before 'y' assimilates towards /ʃ/."},
            {"text": "black coffee", "pattern": "bla(ck) coffee", "note": "Identical consonants: hold the 'k', don't release twice."},
            {"text": "bad day", "pattern": "ba(d) day", "note": "Geminate 'd': hold and release once into 'day'."},
            {"text": "good deal", "pattern": "goo(d) deal", "note": "Hold the 'd' from 'good' and release on 'deal'."},
            {"text": "hot tea", "pattern": "ho(t) tea", "note": "Don't say 'hot-uh tea'; hold the 't' stop directly."},
            {"text": "stop pushing", "pattern": "sto(p) pushing", "note": "Hold the lips closed for 'p' and release once into 'pushing'."},
            {"text": "big game", "pattern": "bi(g) game", "note": "Single velar stop: hold 'g' across both words."},
            {"text": "next door", "pattern": "nex(t) door", "note": "Elision: the 't' in 'next' is elided before consonant 'd'."},
            {"text": "last night", "pattern": "las(t) night", "note": "Elision: 'last' drops the 't' when spoken naturally."},
            {"text": "give it a try", "pattern": "gi-vi-ta-try", "note": "Four words linked into one continuous stream of speech."}
        ]
    },
    "reductions": {
        "title": "Practice",
        "level": "intermediate",
        "difficulty": "medium",
        "accent": "us",
        "explain": "Master English reductions and weak forms across 50 real-life examples: reducing prepositions, conjunctions, and auxiliaries to schwa /ə/, plus natural informal contractions like gonna, wanna, gotta.",
        "points": [
            "Function words (to, for, at, of, from, can, have, and) weaken to schwa in normal connected speech.",
            "Pronouns (you, him, her, them) frequently drop their initial sounds in rapid speech.",
            "Reduced forms sound more natural, relaxed, and easier to understand to native ears."
        ],
        "caution": "Do not reduce words when they carry strong contrast or appear at the end of a sentence.",
        "items": [
            {"text": "I'm going to call him.", "pattern": "I'm gonna call 'im.", "note": "'going to' reduces to 'gonna', 'him' drops the 'h'."},
            {"text": "I want to go home.", "pattern": "I wanna go home.", "note": "'want to' reduces to 'wanna'."},
            {"text": "I have got to go now.", "pattern": "I gotta go now.", "note": "'got to' contracts to 'gotta'."},
            {"text": "What do you want to do?", "pattern": "Whaddya wanna do?", "note": "High-frequency reduction of 'what do you want to'."},
            {"text": "Let me see that.", "pattern": "Lemme see that.", "note": "'let me' reduces to 'lemme'."},
            {"text": "Give me a minute.", "pattern": "Gimme a minute.", "note": "'give me' reduces to 'gimme'."},
            {"text": "I should have told you.", "pattern": "I shoulda told ya.", "note": "'should have' reduces to 'shoulda', 'you' to 'ya'."},
            {"text": "She could have won the race.", "pattern": "She coulda won the race.", "note": "'could have' reduces to 'coulda'."},
            {"text": "We would have helped you.", "pattern": "We woulda helped ya.", "note": "'would have' reduces to 'woulda'."},
            {"text": "You must have heard the news.", "pattern": "You musta heard the news.", "note": "'must have' reduces to 'musta'."},
            {"text": "He kind of likes it.", "pattern": "He kinda likes it.", "note": "'kind of' reduces to 'kinda'."},
            {"text": "It's sort of funny.", "pattern": "It's sorta funny.", "note": "'sort of' reduces to 'sorta'."},
            {"text": "There are a lot of people.", "pattern": "There are a lotta people.", "note": "'lot of' reduces to 'lotta'."},
            {"text": "Get out of here.", "pattern": "Get outta here.", "note": "'out of' reduces to 'outta'."},
            {"text": "Don't you know?", "pattern": "Doncha know?", "note": "'don't you' contracts to 'doncha'."},
            {"text": "I don't know what to say.", "pattern": "I dunno whatta say.", "note": "'don't know' contracts to 'dunno', 'what to' to 'whatta'."},
            {"text": "Did you eat yet?", "pattern": "Jeet yet?", "note": "Extremely fast colloquial reduction: 'did you eat' -> 'jeet'."},
            {"text": "I have to leave now.", "pattern": "I hafta leave now.", "note": "'have to' pronounced with voiceless /f/: 'hafta'."},
            {"text": "She has to study tonight.", "pattern": "She hasta study tonight.", "note": "'has to' pronounced with voiceless /s/: 'hasta'."},
            {"text": "We used to live there.", "pattern": "We usta live there.", "note": "'used to' reduces to 'usta'."},
            {"text": "I'm going to travel to London.", "pattern": "I'm gonna travel tə London.", "note": "The preposition 'to' reduces to weak schwa /tə/."},
            {"text": "This gift is for you.", "pattern": "This gift is fər you.", "note": "'for' weakens to /fər/."},
            {"text": "We met at the station.", "pattern": "We met ət the station.", "note": "'at' reduces to weak /ət/."},
            {"text": "A cup of coffee, please.", "pattern": "A cup əv coffee, please.", "note": "'of' reduces to /əv/ or just /ə/."},
            {"text": "She comes from Canada.", "pattern": "She comes frəm Canada.", "note": "'from' weakens to /frəm/."},
            {"text": "Fish and chips.", "pattern": "Fish 'n' chips.", "note": "'and' reduces to a syllabic /n/ sound."},
            {"text": "Salt and pepper.", "pattern": "Salt 'n' pepper.", "note": "'and' reduces to 'n'."},
            {"text": "Rock and roll.", "pattern": "Rock 'n' roll.", "note": "'and' is completely reduced to /n/."},
            {"text": "I can do that easily.", "pattern": "I kən do that easily.", "note": "Modal 'can' reduces to /kən/; only stressed when negative (can't)."},
            {"text": "Can you see it?", "pattern": "Kən you see it?", "note": "'can' is weak /kən/."},
            {"text": "I have seen it before.", "pattern": "I've seen it / I əv seen it.", "note": "Auxiliary 'have' reduces to /əv/."},
            {"text": "She has been working hard.", "pattern": "She's been / She əz been.", "note": "Auxiliary 'has' reduces to /əz/."},
            {"text": "They had already left.", "pattern": "They'd / They əd already left.", "note": "Auxiliary 'had' reduces to /əd/."},
            {"text": "Tell him the truth.", "pattern": "Tell 'im the truth.", "note": "Pronoun 'him' drops the 'h': 'tell-im'."},
            {"text": "Give her a call.", "pattern": "Give 'er a call.", "note": "Pronoun 'her' drops the 'h': 'give-er'."},
            {"text": "I asked them yesterday.", "pattern": "I asked 'em yesterday.", "note": "'them' reduces to 'em' /əm/."},
            {"text": "Where is he going?", "pattern": "Where's 'e going?", "note": "'he' drops the /h/ sound in rapid speech."},
            {"text": "What has he done?", "pattern": "What's 'e done?", "note": "'has he' contracts to 'what-zee'."},
            {"text": "Because of the rain.", "pattern": "Cuz əv the rain.", "note": "'because' reduces to 'cuz' /kəz/."},
            {"text": "Are you ready?", "pattern": "Ər you ready?", "note": "'are' reduces to schwa /ər/."},
            {"text": "Was it good?", "pattern": "Wəz it good?", "note": "'was' reduces to weak /wəz/."},
            {"text": "Does he work here?", "pattern": "Dəz 'e work here?", "note": "'does' reduces to /dəz/, 'he' drops 'h'."},
            {"text": "Some of them agreed.", "pattern": "Some əv 'em agreed.", "note": "Both 'of' and 'them' are reduced."},
            {"text": "As soon as possible.", "pattern": "Əz soon əz possible.", "note": "'as' reduces to weak /əz/."},
            {"text": "Than ever before.", "pattern": "Thən ever before.", "note": "'than' reduces to weak /ðən/."},
            {"text": "More than that.", "pattern": "More thən that.", "note": "'than' reduces to /ðən/."},
            {"text": "Just a moment.", "pattern": "Jus' a moment.", "note": "The 't' in 'just' drops before vowel 'a'."},
            {"text": "I used to play tennis.", "pattern": "I useta play tennis.", "note": "'used to' reduces to 'useta'."},
            {"text": "How is it going?", "pattern": "How's it goin'?", "note": "-ing reduces to -in'."},
            {"text": "You shouldn't have done that.", "pattern": "You shouldn't've done that.", "note": "Double contraction: 'shouldn't have' -> 'shouldn't-əv'."}
        ]
    },
    "rhythm": {
        "title": "Practice",
        "level": "intermediate",
        "difficulty": "medium",
        "accent": "us",
        "explain": "Master English stress-timed rhythm across 50 sentences. In English, the beats occur at regular intervals on stressed syllables, while unstressed syllables are compressed to fit the tempo.",
        "points": [
            "English rhythm is like music: keep a steady pulse on the stressed syllables.",
            "Adding more unstressed words does not lengthen the sentence — you squeeze them faster.",
            "Tap your foot or hand to keep time with the primary beats."
        ],
        "caution": "Avoid syllable-timed rhythm (pronouncing every syllable with equal timing like Vietnamese or Spanish).",
        "items": [
            {"text": "CATS CHASE MICE.", "pattern": "1 - 2 - 3 (3 beats, 3 words)", "note": "Three words, three stressed beats; slow, steady tempo."},
            {"text": "The CATS CHASE MICE.", "pattern": "da-1 - 2 - 3 (3 beats, 4 words)", "note": "Takes the exact same amount of time as 'Cats chase mice'."},
            {"text": "The CATS will CHASE the MICE.", "pattern": "da-1 - da-2 - da-3 (3 beats, 6 words)", "note": "Same 3 beats: 'will' and 'the' are compressed."},
            {"text": "The CATS will have CHASED all the MICE.", "pattern": "da-1 - da-da-2 - da-da-3 (3 beats, 8 words)", "note": "Still 3 beats! Unstressed words are squeezed very fast."},
            {"text": "BIRDS SING SONGS.", "pattern": "1 - 2 - 3", "note": "Pure beat on every content word."},
            {"text": "The BIRDS are SING-ing SONGS.", "pattern": "da-1 - da-2-da - 3", "note": "Three beats; unstressed syllables fill the gaps."},
            {"text": "The BIRDS could have been SING-ing their SONGS.", "pattern": "da-1 - da-da-da-2-da - da-3", "note": "The tempo between beats remains steady."},
            {"text": "TIME FLIES FAST.", "pattern": "1 - 2 - 3", "note": "Three strong beats."},
            {"text": "HOW TIME FLIES when you're HAV-ing FUN!", "pattern": "1 - 2 - 3 - da-da-4-da - 5", "note": "Regular rhythmic pulses across the whole idiom."},
            {"text": "BOYS LIKE TOYS.", "pattern": "1 - 2 - 3", "note": "Three monosyllabic beats."},
            {"text": "LIT-tle BOYS like SHIN-y TOYS.", "pattern": "1-da - 2 - da-3-da - 4", "note": "Even spacing between stressed syllables."},
            {"text": "WORK HARD, PLAY HARD.", "pattern": "1 - 2, 3 - 4", "note": "Four punchy, balanced beats."},
            {"text": "EAR-ly to BED and EAR-ly to RISE.", "pattern": "1-da da 2 and 3-da da 4", "note": "Famous proverb with a classic waltz-like rhythm."},
            {"text": "NO PAIN, NO GAIN.", "pattern": "1 - 2, 3 - 4", "note": "Four distinct pulses."},
            {"text": "BET-ter LATE than NEV-er.", "pattern": "1-da 2 than 3-da", "note": "Three stressed pulses."},
            {"text": "EAS-y COME, EAS-y GO.", "pattern": "1-da 2, 3-da 4", "note": "Symmetrical rhythm pattern."},
            {"text": "SPEAK of the DEV-il.", "pattern": "1 of the 2-il", "note": "Two beats; 'of the' takes almost no time."},
            {"text": "A DROP in the O-cean.", "pattern": "a 1 in the 2-cean", "note": "Two main beats: 'drop' and 'ocean'."},
            {"text": "ONCE in a BLUE MOON.", "pattern": "1 in a 2 3", "note": "Notice the triple-beat on 'once', 'blue', 'moon'."},
            {"text": "CALL me when you GET there.", "pattern": "1 me when you 2 there", "note": "Two anchor beats: 'call' and 'get'."},
            {"text": "LEAVE it on the COUN-ter.", "pattern": "1 it on the 2-ter", "note": "Two main pulses: 'leave' and 'counter'."},
            {"text": "TAKE your TIME with the PA-per.", "pattern": "1 your 2 with the 3-per", "note": "Three regular beats."},
            {"text": "MEET me at the STA-tion at FIVE.", "pattern": "1 me at the 2-tion at 3", "note": "Three evenly spaced beats: 'meet', 'station', 'five'."},
            {"text": "PUT the KEYS on the TA-ble.", "pattern": "1 the 2 on the 3-ble", "note": "Three clear drumbeats."},
            {"text": "TURN the LIGHTS OFF when you GO.", "pattern": "1 the 2 3 when you 4", "note": "Steady musical pulse."},
            {"text": "GIVE me a CALL when you AR-RIVE.", "pattern": "1 me a 2 when you ar-3", "note": "Three beats across eight words."},
            {"text": "SEND me the PIC-tures as SOON as you CAN.", "pattern": "1 me the 2-tures as 3 as you 4", "note": "Four rhythmic anchors."},
            {"text": "DROP by the OF-fice to SIGN the CON-tract.", "pattern": "1 by the 2-fice to 3 the 4-tract", "note": "Four regular pulses."},
            {"text": "STOP by the MAR-ket for MILK and BREAD.", "pattern": "1 by the 2-ket for 3 and 4", "note": "Four strong beats."},
            {"text": "WALK down the STREET to the COR-ner STORE.", "pattern": "1 down the 2 to the 3-ner 4", "note": "Steady walking rhythm."},
            {"text": "FIRST COME, FIRST SERVED.", "pattern": "1 2, 3 4", "note": "Four heavy monosyllabic beats."},
            {"text": "LIVE and LEARN.", "pattern": "1 and 2", "note": "Two beats with a squeezed 'and'."},
            {"text": "GIVE and TAKE.", "pattern": "1 and 2", "note": "Two sharp beats."},
            {"text": "MORE or LESS.", "pattern": "1 or 2", "note": "Two beats with unstressed 'or'."},
            {"text": "SOON-er or LA-ter.", "pattern": "1-er or 2-ter", "note": "Trochaic balance: strong-weak, strong-weak."},
            {"text": "NOW or NEV-er.", "pattern": "1 or 2-er", "note": "Two beats: 'now' and 'nev'."},
            {"text": "STEP by STEP.", "pattern": "1 by 2", "note": "Two beats connected by weak 'by'."},
            {"text": "DAY by DAY.", "pattern": "1 by 2", "note": "Regular rhythmic repetition."},
            {"text": "LIT-tle by LIT-tle.", "pattern": "1-tle by 2-tle", "note": "Two primary stresses."},
            {"text": "TIME and a-GAIN.", "pattern": "1 and a-2", "note": "Two beats: 'time' and 'gain'."},
            {"text": "OUT of SIGHT, OUT of MIND.", "pattern": "1 of 2, 3 of 4", "note": "Symmetrical pair of two-beat chunks."},
            {"text": "A BLESS-ing in dis-GUISE.", "pattern": "a 1-ing in dis-2", "note": "Two strong beats: 'bless' and 'guise'."},
            {"text": "A PIECE of CAKE.", "pattern": "a 1 of 2", "note": "Two beats: 'piece' and 'cake'."},
            {"text": "BREAK a LEG.", "pattern": "1 a 2", "note": "Two strong beats."},
            {"text": "COST an ARM and a LEG.", "pattern": "1 an 2 and a 3", "note": "Three beats: 'cost', 'arm', 'leg'."},
            {"text": "HIT the NAIL on the HEAD.", "pattern": "1 the 2 on the 3", "note": "Three sharp hammer beats."},
            {"text": "UNDER the WEATH-er.", "pattern": "1-der the 2-er", "note": "Two beats: 'un' and 'weath'."},
            {"text": "SEE EYE to EYE.", "pattern": "1 2 to 3", "note": "Three consecutive beats."},
            {"text": "BACK to the DRAW-ing BOARD.", "pattern": "1 to the 2-ing 3", "note": "Three beats: 'back', 'draw', 'board'."},
            {"text": "A WALK in the PARK.", "pattern": "a 1 in the 2", "note": "Two rhythmic beats: 'walk' and 'park'."}
        ]
    },
    "chunking": {
        "title": "Practice",
        "level": "intermediate",
        "difficulty": "medium",
        "accent": "us",
        "explain": "Master pausing and chunking across 50 complex sentences. Group words into meaningful thought units and insert clean, micro-pauses at natural grammatical boundaries.",
        "points": [
            "Chunk words into grammatical units: subject phrase / verb phrase / prepositional phrase.",
            "Pause briefly (/) at punctuation and before conjunctions (and, but, because, although).",
            "Never breathe or pause in the middle of a tightly knit phrase (e.g. between adjective and noun)."
        ],
        "caution": "Pausing in the wrong place confuses listeners even if every individual word is pronounced correctly.",
        "items": [
            {"text": "When you arrive at the hotel / please call me right away.", "pattern": "When you arrive at the hotel / please call me right away.", "note": "Pause after the introductory dependent clause."},
            {"text": "If it rains tomorrow / we'll have to reschedule the match.", "pattern": "If it rains tomorrow / we'll have to reschedule the match.", "note": "Pause after the conditional clause."},
            {"text": "Although he worked late / he still woke up early for the meeting.", "pattern": "Although he worked late / he still woke up early / for the meeting.", "note": "Two natural pause boundaries."},
            {"text": "Because the train was delayed / I missed my morning appointment.", "pattern": "Because the train was delayed / I missed my morning appointment.", "note": "Clear pause after the causal clause."},
            {"text": "Unless we hear from them today / we will proceed with the original plan.", "pattern": "Unless we hear from them today / we will proceed / with the original plan.", "note": "Pause after the condition."},
            {"text": "The manager / who hired me last year / has just been promoted.", "pattern": "The manager / who hired me last year / has just been promoted.", "note": "Pauses isolate the non-defining relative clause."},
            {"text": "My older brother / who lives in Seattle / is visiting this weekend.", "pattern": "My older brother / who lives in Seattle / is visiting this weekend.", "note": "Chunk the relative clause as an independent unit."},
            {"text": "The book that I borrowed from you / was absolutely fascinating.", "pattern": "The book that I borrowed from you / was absolutely fascinating.", "note": "Pause after the long subject noun phrase."},
            {"text": "The woman sitting next to the window / is our new director.", "pattern": "The woman sitting next to the window / is our new director.", "note": "Pause separates the extended subject from the verb."},
            {"text": "Everything you told me yesterday / turned out to be completely true.", "pattern": "Everything you told me yesterday / turned out to be completely true.", "note": "Pause after the subject clause."},
            {"text": "To be completely honest with you / I don't think it's going to work.", "pattern": "To be completely honest with you / I don't think / it's going to work.", "note": "Introductory conversational formula forms its own chunk."},
            {"text": "As far as I know / the store is open until nine o'clock.", "pattern": "As far as I know / the store is open / until nine o'clock.", "note": "Parenthetical opener is a distinct thought group."},
            {"text": "In my personal opinion / we should invest more in customer support.", "pattern": "In my personal opinion / we should invest more / in customer support.", "note": "Pause after the opinion phrase."},
            {"text": "On the other hand / there are several significant risks to consider.", "pattern": "On the other hand / there are several significant risks / to consider.", "note": "Transition phrase forms its own clean chunk."},
            {"text": "First of all / let me thank everyone for coming today.", "pattern": "First of all / let me thank everyone / for coming today.", "note": "Signpost phrase stands alone."},
            {"text": "According to the latest report / sales have increased by fifteen percent.", "pattern": "According to the latest report / sales have increased / by fifteen percent.", "note": "Attribution phrase followed by a pause."},
            {"text": "At the end of the day / results are what matter most.", "pattern": "At the end of the day / results are what matter most.", "note": "Introductory idiom chunked separately."},
            {"text": "Believe it or not / he finished the entire marathon in under three hours.", "pattern": "Believe it or not / he finished the entire marathon / in under three hours.", "note": "Opening chunk sets the mood."},
            {"text": "By the way / did you receive the package I sent last week?", "pattern": "By the way / did you receive the package / I sent last week?", "note": "Conversational transition followed by a pause."},
            {"text": "From what I understand / the deadline has been extended until Friday.", "pattern": "From what I understand / the deadline has been extended / until Friday.", "note": "Opening qualification chunk."},
            {"text": "We wanted to visit the museum / but the tickets were completely sold out.", "pattern": "We wanted to visit the museum / but the tickets were completely sold out.", "note": "Pause before coordinating conjunction 'but'."},
            {"text": "She studied hard for months / so she passed the exam with flying colors.", "pattern": "She studied hard for months / so she passed the exam / with flying colors.", "note": "Pause before result conjunction 'so'."},
            {"text": "You can take the bus / or you can take the subway / but the subway is faster.", "pattern": "You can take the bus / or you can take the subway / but the subway is faster.", "note": "Pause between contrasting coordinates."},
            {"text": "I really wanted to help / yet there was nothing I could do.", "pattern": "I really wanted to help / yet there was nothing / I could do.", "note": "Pause before 'yet'."},
            {"text": "Not only did he arrive late / but he also forgot his laptop.", "pattern": "Not only did he arrive late / but he also forgot his laptop.", "note": "Correlative conjunction boundary."},
            {"text": "During the summer vacation / my family and I traveled through Europe.", "pattern": "During the summer vacation / my family and I / traveled through Europe.", "note": "Time phrase chunk followed by subject chunk."},
            {"text": "After graduating from university / she started working at a law firm.", "pattern": "After graduating from university / she started working / at a law firm.", "note": "Prepositional time clause forms a chunk."},
            {"text": "Before you make a final decision / take some time to think it over.", "pattern": "Before you make a final decision / take some time / to think it over.", "note": "Pause between condition and advice."},
            {"text": "While I was walking in the park / I ran into an old classmate from school.", "pattern": "While I was walking in the park / I ran into an old classmate / from school.", "note": "Simultaneous time clause chunk."},
            {"text": "Since we moved to this neighborhood / our commute has become much shorter.", "pattern": "Since we moved to this neighborhood / our commute / has become much shorter.", "note": "Causal/time clause boundary."},
            {"text": "The presentation was informative / engaging / and exceptionally well organized.", "pattern": "The presentation was informative / engaging / and exceptionally well organized.", "note": "Pauses separate the parallel adjectives in the list."},
            {"text": "We need milk / eggs / a loaf of bread / and some fresh fruit.", "pattern": "We need milk / eggs / a loaf of bread / and some fresh fruit.", "note": "Micro-pauses between shopping items."},
            {"text": "She packed her clothes / grabbed her passport / and rushed out the door.", "pattern": "She packed her clothes / grabbed her passport / and rushed out the door.", "note": "Action sequence chunking."},
            {"text": "I checked my email / replied to urgent messages / and started writing the report.", "pattern": "I checked my email / replied to urgent messages / and started writing the report.", "note": "Sequential verb phrases separated by pauses."},
            {"text": "He looked to the left / then to the right / and carefully crossed the road.", "pattern": "He looked to the left / then to the right / and carefully crossed the road.", "note": "Three-part action sequence."},
            {"text": "She said / 'I will never give up on my dreams.'", "pattern": "She said / 'I will never give up / on my dreams.'", "note": "Pause before direct quotation."},
            {"text": "'If you need assistance,' / he explained, / 'please contact the front desk.'", "pattern": "'If you need assistance,' / he explained / 'please contact the front desk.'", "note": "Dialogue attribution chunked distinctly."},
            {"text": "The teacher looked at the class / and whispered / 'Pay close attention.'", "pattern": "The teacher looked at the class / and whispered / 'Pay close attention.'", "note": "Dramatic pause before the whispered quote."},
            {"text": "'We made it,' / she smiled, / 'just in the nick of time.'", "pattern": "'We made it' / she smiled / 'just in the nick of time.'", "note": "Split quotation rhythm."},
            {"text": "He paused for a second / and then replied / 'I completely agree.'", "pattern": "He paused for a second / and then replied / 'I completely agree.'", "note": "Pause before direct answer."},
            {"text": "The problem / as I see it / is a lack of clear communication.", "pattern": "The problem / as I see it / is a lack of clear communication.", "note": "Parenthetical insertion surrounded by micro-pauses."},
            {"text": "This method / however / requires significantly more time and patience.", "pattern": "This method / however / requires significantly more time / and patience.", "note": "Conjunctive adverb 'however' set apart by pauses."},
            {"text": "The results / therefore / should be interpreted with extreme caution.", "pattern": "The results / therefore / should be interpreted / with extreme caution.", "note": "Transitions chunked cleanly."},
            {"text": "Her performance / in fact / exceeded all our expectations.", "pattern": "Her performance / in fact / exceeded all our expectations.", "note": "'in fact' isolated by brief pauses."},
            {"text": "The system / for the most part / runs smoothly without human intervention.", "pattern": "The system / for the most part / runs smoothly / without human intervention.", "note": "Modifier chunked in the middle."},
            {"text": "Whatever you decide to do / make sure you commit to it fully.", "pattern": "Whatever you decide to do / make sure / you commit to it fully.", "note": "Free relative clause chunk."},
            {"text": "Whoever left their jacket in the conference room / can collect it from reception.", "pattern": "Whoever left their jacket in the conference room / can collect it / from reception.", "note": "Extended subject clause boundary."},
            {"text": "Wherever you go in the world / you will always find friendly people.", "pattern": "Wherever you go in the world / you will always find / friendly people.", "note": "Adverbial clause chunk."},
            {"text": "However difficult the challenge may seem / we must remain optimistic.", "pattern": "However difficult the challenge may seem / we must remain optimistic.", "note": "Concessive clause boundary."},
            {"text": "Whenever you feel overwhelmed / take a deep breath and take one step at a time.", "pattern": "Whenever you feel overwhelmed / take a deep breath / and take one step at a time.", "note": "Three balanced, calm thought groups."}
        ]
    },
    "fluency": {
        "title": "Practice",
        "level": "intermediate",
        "difficulty": "medium",
        "accent": "us",
        "explain": "Master spoken fluency, flow, and smooth articulation across 50 full conversational sentences. Focus on maintaining a steady rhythm, breath support, and seamless vocal transitions without hesitation.",
        "points": [
            "Maintain continuous vocal support: speak in full breath phrases rather than word by word.",
            "Connect words smoothly without robotic pauses or throat tension.",
            "Focus on the overall message and communicative flow rather than individual syllables."
        ],
        "caution": "Fluency is not speaking as fast as possible; it is speaking smoothly at an effortless, steady pace.",
        "items": [
            {"text": "Could you tell me how to get to the nearest subway station?", "pattern": "Could you tell me how to get / to the nearest subway station?", "note": "Flow smoothly through 'how to get to the'."},
            {"text": "I was wondering if you might have a few minutes to talk.", "pattern": "I was wondering / if you might have a few minutes to talk.", "note": "Polite conversational opening with effortless glide."},
            {"text": "It's been a really long time since we last caught up.", "pattern": "It's been a really long time / since we last caught up.", "note": "Natural conversational cadence."},
            {"text": "Thank you so much for taking the time to meet with me today.", "pattern": "Thank you so much / for taking the time / to meet with me today.", "note": "Professional opening spoken in three smooth waves."},
            {"text": "I'd love to join you for dinner, but I have a prior engagement.", "pattern": "I'd love to join you for dinner / but I have a prior engagement.", "note": "Polite social refusal with continuous voice."},
            {"text": "To be completely honest, that never even crossed my mind.", "pattern": "To be completely honest / that never even crossed my mind.", "note": "Idiom flows as a single acoustic gesture."},
            {"text": "I'm having a hard time hearing you over the background noise.", "pattern": "I'm having a hard time hearing you / over the background noise.", "note": "Practical teleconference sentence."},
            {"text": "Let me know if there's anything else I can do to help.", "pattern": "Let me know / if there's anything else / I can do to help.", "note": "Friendly closing spoken with open vowels."},
            {"text": "I really appreciate your quick response to my inquiry.", "pattern": "I really appreciate / your quick response / to my inquiry.", "note": "Professional customer service flow."},
            {"text": "Sorry for keeping you waiting; the traffic was absolutely terrible.", "pattern": "Sorry for keeping you waiting / the traffic was absolutely terrible.", "note": "Apology and explanation linked naturally."},
            {"text": "One of the most important things in life is continuous learning.", "pattern": "One of the most important things in life / is continuous learning.", "note": "Reflective thought delivered with steady pace."},
            {"text": "In recent years, technology has transformed the way we work.", "pattern": "In recent years / technology has transformed / the way we work.", "note": "IELTS-style essay topic sentence spoken smoothly."},
            {"text": "From my perspective, there are both advantages and disadvantages.", "pattern": "From my perspective / there are both advantages / and disadvantages.", "note": "Classic analytical opening spoken in balanced chunks."},
            {"text": "The main reason why people travel is to experience different cultures.", "pattern": "The main reason why people travel / is to experience different cultures.", "note": "Flow through 'reason why people travel'."},
            {"text": "It is widely believed that regular exercise improves mental well-being.", "pattern": "It is widely believed / that regular exercise / improves mental well-being.", "note": "Academic passive flow."},
            {"text": "I've always had a strong passion for music and creative arts.", "pattern": "I've always had a strong passion / for music and creative arts.", "note": "Personal interview response delivered naturally."},
            {"text": "When I was growing up, we used to spend our summers at the lake.", "pattern": "When I was growing up / we used to spend our summers / at the lake.", "note": "Nostalgic storytelling rhythm."},
            {"text": "That experience taught me the value of patience and perseverance.", "pattern": "That experience taught me / the value of patience / and perseverance.", "note": "Fluency through multi-syllable abstract nouns."},
            {"text": "If I had the chance to do it all over again, I wouldn't change a thing.", "pattern": "If I had the chance to do it all over again / I wouldn't change a thing.", "note": "Conditional reflection spoken without hesitations."},
            {"text": "Looking back, that was probably one of the best decisions I've ever made.", "pattern": "Looking back / that was probably one of the best decisions / I've ever made.", "note": "Conversational reflection flowing into a superlative."},
            {"text": "First, let's take a look at the key findings from our survey.", "pattern": "First / let's take a look / at the key findings / from our survey.", "note": "Presentation transition."},
            {"text": "Moving on to our next topic, I'd like to discuss the budget.", "pattern": "Moving on to our next topic / I'd like to discuss the budget.", "note": "Signposting phrase spoken with clean articulation."},
            {"text": "As you can see from this chart, sales peaked in the third quarter.", "pattern": "As you can see from this chart / sales peaked / in the third quarter.", "note": "Data description fluency."},
            {"text": "To summarize briefly, we need to focus on efficiency and innovation.", "pattern": "To summarize briefly / we need to focus / on efficiency and innovation.", "note": "Concluding presentation flow."},
            {"text": "If anyone has any questions, I'd be more than happy to answer them.", "pattern": "If anyone has any questions / I'd be more than happy / to answer them.", "note": "Q&A invitation delivered warmly."},
            {"text": "I'm calling to see if my order has already been shipped.", "pattern": "I'm calling to see / if my order has already been shipped.", "note": "Everyday phone inquiry flow."},
            {"text": "Could you please hold the line while I transfer your call?", "pattern": "Could you please hold the line / while I transfer your call?", "note": "Customer support fluency."},
            {"text": "I'd like to make a reservation for a party of four this Saturday evening.", "pattern": "I'd like to make a reservation / for a party of four / this Saturday evening.", "note": "Restaurant booking with uninterrupted rhythm."},
            {"text": "Is there any chance we could get a table by the window?", "pattern": "Is there any chance / we could get a table / by the window?", "note": "Polite request flowing without awkward breaks."},
            {"text": "Could we please have the bill whenever you have a moment?", "pattern": "Could we please have the bill / whenever you have a moment?", "note": "Natural restaurant checkout phrase."},
            {"text": "I'm sorry to bother you, but I think you dropped your wallet.", "pattern": "I'm sorry to bother you / but I think you dropped your wallet.", "note": "Spontaneous polite interaction."},
            {"text": "Excuse me, do you happen to know what time the library closes?", "pattern": "Excuse me / do you happen to know / what time the library closes?", "note": "Polite street inquiry with indirect question flow."},
            {"text": "Would you mind keeping an eye on my bag for just a second?", "pattern": "Would you mind keeping an eye on my bag / for just a second?", "note": "Natural idiom 'keeping an eye on'."},
            {"text": "I was wondering whether you could recommend a good Italian restaurant nearby.", "pattern": "I was wondering / whether you could recommend / a good Italian restaurant nearby.", "note": "High-level polite recommendation request."},
            {"text": "Thanks for the recommendation; that was hands down the best pasta I've tasted.", "pattern": "Thanks for the recommendation / that was hands down / the best pasta I've tasted.", "note": "Enthusiastic compliment delivered smoothly."},
            {"text": "As far as I'm concerned, the advantages far outweigh the disadvantages.", "pattern": "As far as I'm concerned / the advantages / far outweigh the disadvantages.", "note": "Debate phrase spoken with authoritative cadence."},
            {"text": "It goes without saying that hard work is essential for long-term success.", "pattern": "It goes without saying / that hard work is essential / for long-term success.", "note": "Smooth transition through 'goes without saying'."},
            {"text": "I couldn't agree more with the points that were raised earlier.", "pattern": "I couldn't agree more / with the points / that were raised earlier.", "note": "Strong agreement in meeting context."},
            {"text": "I see your point, but we also have to take the costs into consideration.", "pattern": "I see your point / but we also have to take the costs / into consideration.", "note": "Diplomatic disagreement delivered politely."},
            {"text": "That's an interesting perspective, although I look at it a bit differently.", "pattern": "That's an interesting perspective / although I look at it / a bit differently.", "note": "Thoughtful negotiation rhythm."},
            {"text": "The sooner we get started, the sooner we'll be able to finish.", "pattern": "The sooner we get started / the sooner we'll be able to finish.", "note": "Parallel comparative structure: 'the sooner... the sooner...'."},
            {"text": "Not only is it cost-effective, but it's also environmentally friendly.", "pattern": "Not only is it cost-effective / but it's also / environmentally friendly.", "note": "Correlative conjunction flow."},
            {"text": "No matter how difficult things get, we have to keep pushing forward.", "pattern": "No matter how difficult things get / we have to keep pushing forward.", "note": "Encouraging statement delivered with strength."},
            {"text": "Under no circumstances should you share your password with anyone.", "pattern": "Under no circumstances / should you share your password / with anyone.", "note": "Formal inverted structure with clear pauses."},
            {"text": "Had I known about the schedule change, I would have arrived much earlier.", "pattern": "Had I known about the schedule change / I would have arrived / much earlier.", "note": "Third conditional inversion flowing smoothly."},
            {"text": "I'm confident that with the right preparation, we can achieve great results.", "pattern": "I'm confident / that with the right preparation / we can achieve great results.", "note": "Motivational speech flow."},
            {"text": "Let's take a quick five-minute coffee break before we tackle the next section.", "pattern": "Let's take a quick five-minute coffee break / before we tackle the next section.", "note": "Informal workplace communication."},
            {"text": "It was truly a pleasure meeting you, and I look forward to working together.", "pattern": "It was truly a pleasure meeting you / and I look forward / to working together.", "note": "Professional closing phrase."},
            {"text": "Please don't hesitate to reach out if you need any further information.", "pattern": "Please don't hesitate to reach out / if you need / any further information.", "note": "Business email/closing formula spoken naturally."},
            {"text": "Consistency and dedication are the true secrets to mastering spoken English.", "pattern": "Consistency and dedication / are the true secrets / to mastering spoken English.", "note": "Inspiring final sentence with complete vocal harmony."}
        ]
    }
}

def main():
    base_dir = "scripts/seed/pronunciation-lessons"
    for skill, lesson_data in PRACTICE_LESSONS.items():
        file_path = os.path.join(base_dir, f"{skill}.json")
        if not os.path.exists(file_path):
            print(f"File not found: {file_path}")
            continue
        with open(file_path, "r", encoding="utf-8") as f:
            doc = json.load(f)

        lessons = doc.get("lessons", [])
        # Check if already exists
        existing_idx = None
        for idx, l in enumerate(lessons):
            if l.get("title") == "Practice":
                existing_idx = idx
                break

        if existing_idx is not None:
            print(f"Updating existing 'Practice' lesson in {file_path}")
            lessons[existing_idx] = lesson_data
        else:
            print(f"Appending 'Practice' lesson (#{len(lessons)+1}) to {file_path}")
            lessons.append(lesson_data)

        doc["lessons"] = lessons
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(doc, f, ensure_ascii=False, indent=2)

        print(f"  -> Total lessons in {skill}: {len(lessons)}, items in Practice: {len(lesson_data['items'])}")

if __name__ == "__main__":
    main()
