/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiSpeakingRouteImport } from './routes/ai-speaking'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as DailyEnglishRouteImport } from './routes/daily-english'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ListeningLabRouteImport } from './routes/listening-lab'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PronunciationRouteImport } from './routes/pronunciation'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ShadowingRouteImport } from './routes/shadowing'
import { Route as SpeakingTestsRouteImport } from './routes/speaking-tests'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth_.google-callback'
import { Route as AuthVerifyRouteImport } from './routes/auth_.verify'
import { Route as BillingCancelledRouteImport } from './routes/billing_.cancelled'
import { Route as BillingSuccessRouteImport } from './routes/billing_.success'
import { Route as CheckoutCancelledRouteImport } from './routes/checkout/cancelled'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSpeakingRoute = AiSpeakingRouteImport.update({
  id: '/ai-speaking',
  path: '/ai-speaking',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyEnglishRoute = DailyEnglishRouteImport.update({
  id: '/daily-english',
  path: '/daily-english',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ListeningLabRoute = ListeningLabRouteImport.update({
  id: '/listening-lab',
  path: '/listening-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PronunciationRoute = PronunciationRouteImport.update({
  id: '/pronunciation',
  path: '/pronunciation',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadowingRoute = ShadowingRouteImport.update({
  id: '/shadowing',
  path: '/shadowing',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakingTestsRoute = SpeakingTestsRouteImport.update({
  id: '/speaking-tests',
  path: '/speaking-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth_/google-callback',
  path: '/auth/google-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth_/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingCancelledRoute = BillingCancelledRouteImport.update({
  id: '/billing_/cancelled',
  path: '/billing/cancelled',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/billing_/success',
  path: '/billing/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelledRoute = CheckoutCancelledRouteImport.update({
  id: '/checkout/cancelled',
  path: '/checkout/cancelled',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/ai-speaking': typeof AiSpeakingRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/daily-english': typeof DailyEnglishRoute
  '/dashboard': typeof DashboardRoute
  '/listening-lab': typeof ListeningLabRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/pronunciation': typeof PronunciationRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shadowing': typeof ShadowingRoute
  '/speaking-tests': typeof SpeakingTestsRoute
  '/terms': typeof TermsRoute
  '/vocabulary': typeof VocabularyRoute
  '/auth/google-callback': typeof AuthGoogleCallbackRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/billing/cancelled': typeof BillingCancelledRoute
  '/billing/success': typeof BillingSuccessRoute
  '/checkout/cancelled': typeof CheckoutCancelledRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/ai-speaking': typeof AiSpeakingRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/daily-english': typeof DailyEnglishRoute
  '/dashboard': typeof DashboardRoute
  '/listening-lab': typeof ListeningLabRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/pronunciation': typeof PronunciationRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shadowing': typeof ShadowingRoute
  '/speaking-tests': typeof SpeakingTestsRoute
  '/terms': typeof TermsRoute
  '/vocabulary': typeof VocabularyRoute
  '/auth/google-callback': typeof AuthGoogleCallbackRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/billing/cancelled': typeof BillingCancelledRoute
  '/billing/success': typeof BillingSuccessRoute
  '/checkout/cancelled': typeof CheckoutCancelledRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/ai-speaking': typeof AiSpeakingRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/daily-english': typeof DailyEnglishRoute
  '/dashboard': typeof DashboardRoute
  '/listening-lab': typeof ListeningLabRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/pronunciation': typeof PronunciationRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shadowing': typeof ShadowingRoute
  '/speaking-tests': typeof SpeakingTestsRoute
  '/terms': typeof TermsRoute
  '/vocabulary': typeof VocabularyRoute
  '/auth_/google-callback': typeof AuthGoogleCallbackRoute
  '/auth_/verify': typeof AuthVerifyRoute
  '/billing_/cancelled': typeof BillingCancelledRoute
  '/billing_/success': typeof BillingSuccessRoute
  '/checkout/cancelled': typeof CheckoutCancelledRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/ai-speaking'
    | '/auth'
    | '/billing'
    | '/daily-english'
    | '/dashboard'
    | '/listening-lab'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/progress'
    | '/pronunciation'
    | '/refunds'
    | '/reset-password'
    | '/shadowing'
    | '/speaking-tests'
    | '/terms'
    | '/vocabulary'
    | '/auth/google-callback'
    | '/auth/verify'
    | '/billing/cancelled'
    | '/billing/success'
    | '/checkout/cancelled'
    | '/checkout/success'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/ai-speaking'
    | '/auth'
    | '/billing'
    | '/daily-english'
    | '/dashboard'
    | '/listening-lab'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/progress'
    | '/pronunciation'
    | '/refunds'
    | '/reset-password'
    | '/shadowing'
    | '/speaking-tests'
    | '/terms'
    | '/vocabulary'
    | '/auth/google-callback'
    | '/auth/verify'
    | '/billing/cancelled'
    | '/billing/success'
    | '/checkout/cancelled'
    | '/checkout/success'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/ai-speaking'
    | '/auth'
    | '/billing'
    | '/daily-english'
    | '/dashboard'
    | '/listening-lab'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/progress'
    | '/pronunciation'
    | '/refunds'
    | '/reset-password'
    | '/shadowing'
    | '/speaking-tests'
    | '/terms'
    | '/vocabulary'
    | '/auth_/google-callback'
    | '/auth_/verify'
    | '/billing_/cancelled'
    | '/billing_/success'
    | '/checkout/cancelled'
    | '/checkout/success'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AiSpeakingRoute: typeof AiSpeakingRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  DailyEnglishRoute: typeof DailyEnglishRoute
  DashboardRoute: typeof DashboardRoute
  ListeningLabRoute: typeof ListeningLabRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgressRoute: typeof ProgressRoute
  PronunciationRoute: typeof PronunciationRoute
  RefundsRoute: typeof RefundsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShadowingRoute: typeof ShadowingRoute
  SpeakingTestsRoute: typeof SpeakingTestsRoute
  TermsRoute: typeof TermsRoute
  VocabularyRoute: typeof VocabularyRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  BillingCancelledRoute: typeof BillingCancelledRoute
  BillingSuccessRoute: typeof BillingSuccessRoute
  CheckoutCancelledRoute: typeof CheckoutCancelledRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-speaking': {
      id: '/ai-speaking'
      path: '/ai-speaking'
      fullPath: '/ai-speaking'
      preLoaderRoute: typeof AiSpeakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-english': {
      id: '/daily-english'
      path: '/daily-english'
      fullPath: '/daily-english'
      preLoaderRoute: typeof DailyEnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listening-lab': {
      id: '/listening-lab'
      path: '/listening-lab'
      fullPath: '/listening-lab'
      preLoaderRoute: typeof ListeningLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronunciation': {
      id: '/pronunciation'
      path: '/pronunciation'
      fullPath: '/pronunciation'
      preLoaderRoute: typeof PronunciationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shadowing': {
      id: '/shadowing'
      path: '/shadowing'
      fullPath: '/shadowing'
      preLoaderRoute: typeof ShadowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaking-tests': {
      id: '/speaking-tests'
      path: '/speaking-tests'
      fullPath: '/speaking-tests'
      preLoaderRoute: typeof SpeakingTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/google-callback': {
      id: '/auth_/google-callback'
      path: '/auth/google-callback'
      fullPath: '/auth/google-callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/verify': {
      id: '/auth_/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing_/cancelled': {
      id: '/billing_/cancelled'
      path: '/billing/cancelled'
      fullPath: '/billing/cancelled'
      preLoaderRoute: typeof BillingCancelledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing_/success': {
      id: '/billing_/success'
      path: '/billing/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancelled': {
      id: '/checkout/cancelled'
      path: '/checkout/cancelled'
      fullPath: '/checkout/cancelled'
      preLoaderRoute: typeof CheckoutCancelledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AiSpeakingRoute: AiSpeakingRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  DailyEnglishRoute: DailyEnglishRoute,
  DashboardRoute: DashboardRoute,
  ListeningLabRoute: ListeningLabRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProgressRoute: ProgressRoute,
  PronunciationRoute: PronunciationRoute,
  RefundsRoute: RefundsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShadowingRoute: ShadowingRoute,
  SpeakingTestsRoute: SpeakingTestsRoute,
  TermsRoute: TermsRoute,
  VocabularyRoute: VocabularyRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  BillingCancelledRoute: BillingCancelledRoute,
  BillingSuccessRoute: BillingSuccessRoute,
  CheckoutCancelledRoute: CheckoutCancelledRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
